"""Safety tests for the source-backed Electron desktop installer."""

from __future__ import annotations

import importlib.util
import io
import json
import plistlib
import re
import stat
import threading
import tomllib
import zipfile
from pathlib import Path

import pytest

VIEWER_DIR = Path(__file__).resolve().parents[1]

# The checkout's real version. `_make_source_bundle` stamps synthetic
# bundles with it, and the installer compares a bundle's stamp against
# the checkout it belongs to -- so a literal here silently turns every
# release into six failing tests, which is exactly what v2.15.3's
# release-candidate pipeline caught. pyproject.toml is the canonical
# source; test_desktop_version_files_stay_in_sync holds the other four
# version sites to it.
VIEWER_VERSION = tomllib.loads(
    (VIEWER_DIR / "pyproject.toml").read_text()
)["project"]["version"]
INSTALLER_PATH = VIEWER_DIR / "electron" / "install-electron.py"


def _load_installer():
    spec = importlib.util.spec_from_file_location(
        "vibeview_install_electron",
        INSTALLER_PATH,
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def installer():
    return _load_installer()


@pytest.fixture
def mac_installer(installer, monkeypatch):
    monkeypatch.setattr(installer.sys, "platform", "darwin")
    monkeypatch.setattr(installer, "_sign_macos_app", lambda *_args, **_kwargs: None)
    return installer


def _make_source_bundle(
    root: Path,
    *,
    checkout: Path = VIEWER_DIR,
    version: str = VIEWER_VERSION,
) -> Path:
    app = root / "Electron.app"
    executable = app / "Contents" / "MacOS" / "Electron"
    executable.parent.mkdir(parents=True)
    executable.write_text("binary\n")
    executable.chmod(0o755)
    info = app / "Contents" / "Info.plist"
    with info.open("wb") as stream:
        plistlib.dump({"CFBundleName": "vibe-view"}, stream)
    app_dir = app / "Contents" / "Resources" / "app"
    app_dir.mkdir(parents=True)
    main_js = checkout / "electron" / "main.js"
    (app_dir / "launcher.js").write_text(
        "// Generated by install-electron.py -- Dock/double-click launcher.\n"
        "// Loads the real vibe-view app from the source checkout that ran\n"
        "// the installer; re-run install-electron.py if the checkout moves.\n"
        f"// vibe-view {version}\n"
        f"require({json.dumps(str(main_js.resolve()))});\n"
    )
    (app_dir / "package.json").write_text(
        json.dumps(
            {
                "name": "vibe-view-launcher",
                "private": True,
                "version": version,
                "main": "launcher.js",
            }
        )
    )
    (app_dir / "vibe-view-source-app.json").write_text(
        json.dumps(
            {
                "schema": 1,
                "kind": "vibe-view-source-desktop",
                "version": version,
                "electron_version": "33.4.11",
                "checkout": str(checkout.resolve()),
            }
        )
    )
    return app


def _make_direct_download_runtime(
    installer,
    root: Path,
    *,
    version: str = "33.4.11",
) -> Path:
    root.mkdir(parents=True)
    (root / "dist").mkdir()
    (root / "vibe-view-electron-version").write_text(version + "\n")
    for name, payload in installer._npm_wrapper_payloads().items():
        (root / name).write_text(payload)
    return root


def test_reviewed_electron_pin_comes_from_lockfile(installer) -> None:
    assert installer.configured_electron_version() == "43.3.0"


@pytest.mark.parametrize(
    ("machine", "expected_arch"),
    (
        ("arm64", "arm64"),
        ("aarch64", "arm64"),
        ("x86_64", "x64"),
        ("amd64", "x64"),
        ("x64", "x64"),
    ),
)
def test_download_url_maps_only_supported_architectures(
    installer,
    monkeypatch,
    machine: str,
    expected_arch: str,
) -> None:
    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(installer.platform, "machine", lambda: machine)

    url = installer.get_download_url("33.4.11")

    assert url.endswith(f"-linux-{expected_arch}.zip")


def test_download_url_rejects_unknown_architecture(installer, monkeypatch) -> None:
    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(installer.platform, "machine", lambda: "riscv64")

    with pytest.raises(RuntimeError, match="Unsupported Electron architecture"):
        installer.get_download_url("33.4.11")


def test_binary_version_probe_uses_node_mode_without_launching_app(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    binary = tmp_path / "electron"
    binary.write_text("placeholder\n")
    commands: list[list[str]] = []
    environments: list[dict[str, str]] = []

    def run(command, **kwargs):
        commands.append(command)
        environments.append(kwargs["env"])
        return installer.subprocess.CompletedProcess(command, 0, "v33.4.11\n", "")

    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(installer.os, "geteuid", lambda: 0, raising=False)
    monkeypatch.setattr(installer.subprocess, "run", run)

    assert installer.electron_binary_version(binary) == "33.4.11"
    assert commands == [[str(binary), "-p", "process.versions.electron"]]
    assert environments[0]["ELECTRON_RUN_AS_NODE"] == "1"


def test_binary_version_probe_preserves_linux_loader_diagnostic(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    binary = tmp_path / "electron"
    binary.write_text("placeholder\n")

    monkeypatch.setattr(
        installer.subprocess,
        "run",
        lambda command, **_kwargs: installer.subprocess.CompletedProcess(
            command,
            127,
            "",
            "error while loading shared libraries: libgtk-3.so.0",
        ),
    )

    version, diagnostic = installer._electron_binary_probe(binary)

    assert version == "unknown"
    assert "libgtk-3.so.0" in diagnostic


def test_linux_runtime_health_distinguishes_missing_desktop_libraries(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    dist = tmp_path / "electron" / "dist"
    binary = dist / "electron"
    binary.parent.mkdir(parents=True)
    binary.write_text("binary\n")
    binary.chmod(0o755)
    (dist.parent / "vibe-view-electron-version").write_text("33.4.11\n")
    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(
        installer,
        "_electron_binary_probe",
        lambda _binary: (
            "unknown",
            "error while loading shared libraries: libgtk-3.so.0",
        ),
    )

    health, diagnostic = installer.electron_runtime_health(dist, "33.4.11")

    assert health == "platform-dependency"
    assert "libgtk-3.so.0" in diagnostic


@pytest.mark.parametrize("member_name", ("../escape", "/absolute/escape"))
def test_python_zip_fallback_rejects_escaping_paths(
    installer,
    tmp_path: Path,
    member_name: str,
) -> None:
    archive_path = tmp_path / "unsafe.zip"
    with zipfile.ZipFile(archive_path, "w") as archive:
        archive.writestr(member_name, "escape\n")
    destination = tmp_path / "dist"
    destination.mkdir()

    with pytest.raises(RuntimeError, match="unsafe path"):
        installer._extract_zip_preserving_permissions(archive_path, destination)

    assert not (tmp_path / "escape").exists()


def test_python_zip_fallback_rejects_escaping_symlink(
    installer,
    tmp_path: Path,
) -> None:
    archive_path = tmp_path / "unsafe-symlink.zip"
    member = zipfile.ZipInfo("nested/link")
    member.create_system = 3
    member.external_attr = (stat.S_IFLNK | 0o777) << 16
    with zipfile.ZipFile(archive_path, "w") as archive:
        archive.writestr(member, "../../escape")
    destination = tmp_path / "dist"
    destination.mkdir()

    with pytest.raises(RuntimeError, match="unsafe symlink"):
        installer._extract_zip_preserving_permissions(archive_path, destination)

    assert not (destination / "nested" / "link").exists()


def test_missing_runtime_uses_reviewed_pin(installer, tmp_path: Path, monkeypatch) -> None:
    reviewed_version = installer.configured_electron_version()
    payload = io.BytesIO()
    with zipfile.ZipFile(payload, "w") as archive:
        for name, content, mode in (
            ("electron", f"#!/bin/sh\nprintf 'v{reviewed_version}\\n'\n", 0o755),
            ("chrome_crashpad_handler", "helper\n", 0o755),
            ("chrome-sandbox", "sandbox\n", 0o4755),
        ):
            member = zipfile.ZipInfo(name)
            member.create_system = 3
            member.external_attr = (stat.S_IFREG | mode) << 16
            archive.writestr(member, content)
        archive.writestr("version", reviewed_version + "\n")
    payload.seek(0)

    class Response:
        headers = {"content-length": str(len(payload.getvalue()))}

        def __init__(self):
            self.stream = io.BytesIO(payload.getvalue())

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self, size: int = -1):
            return self.stream.read(size)

    requested: list[str] = []

    def download_url(version: str) -> str:
        requested.append(version)
        return f"https://example.invalid/electron-v{version}-linux-x64.zip"

    monkeypatch.setattr(installer, "get_download_url", download_url)
    monkeypatch.setattr(
        installer.urllib.request,
        "urlopen",
        lambda _req, **_kwargs: Response(),
    )
    monkeypatch.setattr(installer, "verify_download_checksum", lambda *_args: None)
    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    monkeypatch.setattr(
        installer,
        "finalize_electron_install",
        lambda *_args, **_kwargs: "not-applicable",
    )
    target = tmp_path / "electron"

    installer.install_electron(target_dir=str(target))

    assert requested == [reviewed_version]
    assert (target / "dist" / "electron").exists()
    assert stat.S_IMODE((target / "dist" / "chrome_crashpad_handler").stat().st_mode) == 0o755
    assert stat.S_IMODE((target / "dist" / "chrome-sandbox").stat().st_mode) == 0o4755
    assert (target / "vibe-view-electron-version").read_text() == reviewed_version + "\n"


def test_runtime_record_swap_failure_restores_previous_install(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = io.BytesIO()
    with zipfile.ZipFile(payload, "w") as archive:
        archive.writestr("electron", "#!/bin/sh\nprintf 'v33.4.11\\n'\n")
        archive.writestr("version", "33.4.11\n")

    class Response:
        headers = {"content-length": str(len(payload.getvalue()))}

        def __init__(self):
            self.stream = io.BytesIO(payload.getvalue())

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self, size: int = -1):
            return self.stream.read(size)

    target = tmp_path / "electron"
    old_dist = target / "dist"
    old_dist.mkdir(parents=True)
    (old_dist / "keep.txt").write_text("old runtime\n")
    version_record = target / "vibe-view-electron-version"
    version_record.write_text("32.0.0\n")

    monkeypatch.setattr(
        installer,
        "get_download_url",
        lambda version: f"https://example.invalid/electron-v{version}-linux-x64.zip",
    )
    monkeypatch.setattr(
        installer.urllib.request,
        "urlopen",
        lambda _req, **_kwargs: Response(),
    )
    monkeypatch.setattr(installer, "verify_download_checksum", lambda *_args: None)
    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    real_replace = installer.os.replace
    failed_record_swap = False

    def fail_first_record_swap(source, destination):
        nonlocal failed_record_swap
        if Path(destination) == version_record and not failed_record_swap:
            failed_record_swap = True
            raise OSError("simulated version-record swap failure")
        return real_replace(source, destination)

    monkeypatch.setattr(installer.os, "replace", fail_first_record_swap)

    with pytest.raises(OSError, match="version-record swap failure"):
        installer.install_electron("33.4.11", target_dir=str(target))

    assert (old_dist / "keep.txt").read_text() == "old runtime\n"
    assert not (old_dist / "electron").exists()
    assert version_record.read_text() == "32.0.0\n"


def test_corrupt_present_runtime_is_repaired_to_explicit_version(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    target = tmp_path / "electron"
    binary = target / "dist" / "electron"
    binary.parent.mkdir(parents=True)
    binary.write_bytes(b"")
    binary.chmod(0o755)
    (binary.parent / "version").write_text("34.0.0\n")
    requested: list[str] = []

    def repair(target_path: Path, version: str) -> None:
        requested.append(version)
        binary.write_text("repaired\n")
        binary.chmod(0o755)
        (binary.parent / "version").write_text(version + "\n")

    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")
    monkeypatch.setattr(installer, "_download_and_install_runtime", repair)
    monkeypatch.setattr(
        installer,
        "finalize_electron_install",
        lambda *_args, **_kwargs: "not-applicable",
    )

    status = installer.install_electron("34.0.0", target_dir=str(target))

    assert status == "not-applicable"
    assert requested == ["34.0.0"]


def test_refused_desktop_preflight_leaves_runtime_unchanged(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    target = tmp_path / "electron"
    monkeypatch.setattr(installer.sys, "platform", "darwin")
    monkeypatch.setattr(
        installer,
        "_choose_desktop_app_target",
        lambda **_kwargs: (None, "foreign-source"),
    )

    def unexpected_download(*_args, **_kwargs):
        raise AssertionError("runtime download must happen after ownership preflight")

    monkeypatch.setattr(installer, "_download_and_install_runtime", unexpected_download)

    status = installer.install_electron(
        "33.4.11",
        target_dir=str(target),
        refresh_app=True,
    )

    assert status == "foreign-source"
    assert not (target / "dist").exists()


@pytest.mark.parametrize("status", ("packaged", "unknown", "foreign-source"))
def test_cli_returns_nonzero_when_desktop_refresh_is_refused(
    installer,
    monkeypatch,
    capsys,
    status: str,
) -> None:
    monkeypatch.setattr(
        installer,
        "install_electron",
        lambda *_args, **_kwargs: status,
    )

    assert installer.main(["--refresh-app"]) == 2
    assert f"status: {status}" in capsys.readouterr().err


def test_cli_returns_zero_for_completed_desktop_refresh(
    installer,
    monkeypatch,
) -> None:
    monkeypatch.setattr(
        installer,
        "install_electron",
        lambda *_args, **_kwargs: "installed",
    )

    assert installer.main(["--refresh-app"]) == 0


@pytest.mark.parametrize(("usable", "expected"), ((True, 0), (False, 1)))
def test_cli_check_mode_is_read_only_health_probe(
    installer,
    monkeypatch,
    usable: bool,
    expected: int,
) -> None:
    calls: list[tuple[Path, str]] = []

    def is_usable(path: Path, version: str) -> bool:
        calls.append((path, version))
        return usable

    monkeypatch.setattr(installer, "electron_runtime_is_usable", is_usable)

    assert installer.main(["--check"]) == expected
    assert calls == [
        (
            INSTALLER_PATH.parent / "node_modules" / "electron" / "dist",
            installer.configured_electron_version(),
        )
    ]


def test_cli_check_mode_reports_missing_linux_libraries(
    installer,
    monkeypatch,
    capsys,
) -> None:
    monkeypatch.setattr(installer, "electron_runtime_is_usable", lambda *_args: False)
    monkeypatch.setattr(
        installer,
        "electron_runtime_health",
        lambda *_args: ("platform-dependency", "missing libgtk-3.so.0"),
    )

    assert installer.main(["--check"]) == 2
    assert "missing libgtk-3.so.0" in capsys.readouterr().err


def test_corrupt_runtime_metadata_is_treated_as_unknown(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    dist = tmp_path / "electron" / "dist"
    dist.mkdir(parents=True)
    binary = dist / "electron"
    binary.write_text("not a real executable\n")
    binary.chmod(0o755)
    (dist / "version").write_bytes(b"\xff\xfe")
    monkeypatch.setattr(installer.platform, "system", lambda: "Linux")

    assert installer.electron_runtime_version(dist, include_recorded=False) == "unknown"
    assert not installer.electron_runtime_is_usable(dist, "33.4.11")


def test_existing_runtime_refresh_failure_preserves_original(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    target = tmp_path / "electron"
    dist = target / "dist"
    dist.mkdir(parents=True)
    sentinel = dist / "keep.txt"
    sentinel.write_text("original runtime\n")
    monkeypatch.setattr(installer.platform, "system", lambda: "Darwin")
    monkeypatch.setattr(
        installer,
        "electron_runtime_is_usable",
        lambda *_args, **_kwargs: True,
    )

    def fail_prepare(_dist: Path) -> None:
        raise RuntimeError("simulated staged signing failure")

    monkeypatch.setattr(installer, "prepare_staged_runtime", fail_prepare)

    with pytest.raises(RuntimeError, match="staged signing failure"):
        installer.install_electron("33.4.11", target_dir=str(target))

    assert sentinel.read_text() == "original runtime\n"


def test_installer_lock_serializes_concurrent_refreshes(
    installer,
    tmp_path: Path,
) -> None:
    target = tmp_path / "electron"
    started = threading.Event()
    acquired = threading.Event()

    def contender() -> None:
        started.set()
        with installer.electron_install_lock(target):
            acquired.set()

    with installer.electron_install_lock(target):
        thread = threading.Thread(target=contender)
        thread.start()
        assert started.wait(timeout=1)
        assert not acquired.wait(timeout=0.1)
    thread.join(timeout=2)

    assert acquired.is_set()
    assert not thread.is_alive()


def test_desktop_version_files_stay_in_sync() -> None:
    pyproject = tomllib.loads((VIEWER_DIR / "pyproject.toml").read_text())
    package = json.loads((VIEWER_DIR / "electron" / "package.json").read_text())
    lock = json.loads((VIEWER_DIR / "electron" / "package-lock.json").read_text())
    init_text = (VIEWER_DIR / "src" / "vibeview" / "__init__.py").read_text()
    match = re.search(r'^__version__ = "([^"]+)"', init_text, re.MULTILINE)
    assert match is not None

    expected = pyproject["project"]["version"]
    assert match.group(1) == expected
    assert package["version"] == expected
    assert lock["version"] == expected
    assert lock["packages"][""]["version"] == expected


def test_legacy_launcher_is_recognised_only_for_its_checkout(
    installer,
    tmp_path: Path,
) -> None:
    checkout = tmp_path / "checkout"
    app = _make_source_bundle(tmp_path / "dist", checkout=checkout)
    (app / "Contents" / "Resources" / "app" / "vibe-view-source-app.json").unlink()

    assert installer.desktop_app_kind(app) == "source"
    assert installer.source_app_checkout(app) == checkout.resolve()


def test_marker_and_launcher_must_agree_on_checkout(
    installer,
    tmp_path: Path,
) -> None:
    app = _make_source_bundle(tmp_path / "dist")
    marker_path = installer._source_app_marker(app)
    marker = json.loads(marker_path.read_text())
    marker["checkout"] = str((tmp_path / "other-checkout").resolve())
    marker_path.write_text(json.dumps(marker))

    assert installer.source_app_checkout(app) is None
    assert installer.desktop_app_kind(app) == "unknown"


def test_source_marker_requires_absolute_checkout(installer, tmp_path: Path) -> None:
    app = _make_source_bundle(tmp_path / "dist")
    marker_path = installer._source_app_marker(app)
    marker = json.loads(marker_path.read_text())
    marker["checkout"] = "relative/checkout"
    marker_path.write_text(json.dumps(marker))

    assert installer.desktop_app_kind(app) == "unknown"


def test_dangling_app_symlink_is_unknown(installer, tmp_path: Path) -> None:
    app = tmp_path / "vibe-view.app"
    app.symlink_to(tmp_path / "missing.app")

    assert installer.desktop_app_kind(app) == "unknown"


@pytest.mark.parametrize("sibling_kind", ("packaged", "unknown", "foreign"))
def test_owned_source_app_wins_over_other_applications_candidate(
    installer,
    tmp_path: Path,
    sibling_kind: str,
) -> None:
    system_app = tmp_path / "system" / "vibe-view.app"
    user_app = tmp_path / "user" / "vibe-view.app"
    owned = _make_source_bundle(user_app.parent)
    owned.rename(user_app)
    if sibling_kind == "packaged":
        asar = system_app / "Contents" / "Resources" / "app.asar"
        asar.parent.mkdir(parents=True)
        asar.write_bytes(b"packaged")
    elif sibling_kind == "unknown":
        unknown = system_app / "Contents" / "unknown.txt"
        unknown.parent.mkdir(parents=True)
        unknown.write_text("unknown\n")
    else:
        foreign = _make_source_bundle(
            system_app.parent,
            checkout=tmp_path / "foreign-checkout",
        )
        foreign.rename(system_app)

    selected, kind = installer._choose_desktop_app_target(
        _candidate_paths=(system_app, user_app),
    )

    assert selected == user_app
    assert kind == "source"


def test_launcher_refresh_records_version_and_checkout(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    dist = tmp_path / "runtime" / "dist"
    app = _make_source_bundle(dist)
    app_dir = app / "Contents" / "Resources" / "app"
    for name in ("launcher.js", "vibe-view-source-app.json"):
        (app_dir / name).unlink()
    (app_dir / "package.json").write_text("{}\n")

    installer.write_launcher_shim(dist)

    marker = json.loads(installer._source_app_marker(app).read_text())
    assert marker["schema"] == 1
    assert marker["version"] == installer.project_version()
    assert marker["checkout"] == str(VIEWER_DIR.resolve())
    package = json.loads((app_dir / "package.json").read_text())
    assert package["version"] == installer.project_version()


def test_desktop_app_install_is_not_applicable_off_macos(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    monkeypatch.setattr(installer.sys, "platform", "linux")

    assert installer.install_desktop_app(source_dist, force=True) == "not-applicable"


def test_packaged_app_is_never_replaced(mac_installer, tmp_path: Path) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    packaged = tmp_path / "Applications" / "vibe-view.app"
    asar = packaged / "Contents" / "Resources" / "app.asar"
    asar.parent.mkdir(parents=True)
    asar.write_bytes(b"packaged-sentinel")

    status = installer.install_desktop_app(
        source_dist,
        force=True,
        target_dir=packaged,
    )

    assert status == "packaged"
    assert asar.read_bytes() == b"packaged-sentinel"


def test_unknown_app_is_never_replaced(mac_installer, tmp_path: Path) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    unknown = tmp_path / "Applications" / "vibe-view.app"
    sentinel = unknown / "Contents" / "unknown.txt"
    sentinel.parent.mkdir(parents=True)
    sentinel.write_text("keep me\n")

    status = installer.install_desktop_app(
        source_dist,
        force=True,
        target_dir=unknown,
    )

    assert status == "unknown"
    assert sentinel.read_text() == "keep me\n"


def test_other_checkout_source_app_is_never_adopted(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    foreign = tmp_path / "Applications" / "vibe-view.app"
    _make_source_bundle(foreign.parent, checkout=tmp_path / "other-checkout")
    generated = foreign.parent / "Electron.app"
    generated.rename(foreign)

    status = installer.install_desktop_app(
        source_dist,
        force=True,
        target_dir=foreign,
    )

    assert status == "foreign-source"
    marker = json.loads(installer._source_app_marker(foreign).read_text())
    assert marker["checkout"] == str((tmp_path / "other-checkout").resolve())

    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    adopted = installer.install_desktop_app(
        source_dist,
        force=True,
        target_dir=foreign,
        adopt_app=True,
    )
    assert adopted == "installed"
    marker = json.loads(installer._source_app_marker(foreign).read_text())
    assert marker["checkout"] == str(VIEWER_DIR.resolve())


def test_desktop_target_is_reclassified_after_shared_lock(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"

    class SimulatedRace:
        def __enter__(self):
            generated = _make_source_bundle(
                target.parent,
                checkout=tmp_path / "other-checkout",
            )
            generated.rename(target)

        def __exit__(self, *_args):
            return False

    monkeypatch.setattr(
        installer,
        "desktop_install_lock",
        lambda _destination: SimulatedRace(),
    )

    status = installer.install_desktop_app(
        source_dist,
        force=True,
        target_dir=target,
    )

    assert status == "foreign-source"
    marker = json.loads(installer._source_app_marker(target).read_text())
    assert marker["checkout"] == str((tmp_path / "other-checkout").resolve())


def test_shared_desktop_lock_serializes_checkouts(installer, tmp_path: Path) -> None:
    destination = tmp_path / "Applications" / "vibe-view.app"
    started = threading.Event()
    acquired = threading.Event()

    def contender() -> None:
        started.set()
        with installer.desktop_install_lock(destination):
            acquired.set()

    with installer.desktop_install_lock(destination):
        thread = threading.Thread(target=contender)
        thread.start()
        assert started.wait(timeout=1)
        assert not acquired.wait(timeout=0.1)
    thread.join(timeout=2)

    assert acquired.is_set()
    assert not thread.is_alive()


def test_source_app_refresh_is_idempotent(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"

    first = installer.install_desktop_app(source_dist, target_dir=target)
    second = installer.install_desktop_app(source_dist, target_dir=target)

    assert first == "installed"
    assert second == "current"
    marker = json.loads(installer._source_app_marker(target).read_text())
    assert marker["checkout"] == str(VIEWER_DIR.resolve())


def test_uninstall_removes_all_owned_source_apps_but_preserves_other_kinds(
    mac_installer,
    tmp_path: Path,
) -> None:
    installer = mac_installer
    owned_system = tmp_path / "system" / "vibe-view.app"
    owned_user = tmp_path / "user" / "vibe-view.app"
    foreign = tmp_path / "foreign" / "vibe-view.app"
    packaged = tmp_path / "packaged" / "vibe-view.app"

    for target in (owned_system, owned_user):
        generated = _make_source_bundle(target.parent)
        generated.rename(target)
    generated = _make_source_bundle(
        foreign.parent,
        checkout=tmp_path / "other-checkout",
    )
    generated.rename(foreign)
    asar = packaged / "Contents" / "Resources" / "app.asar"
    asar.parent.mkdir(parents=True)
    asar.write_bytes(b"packaged")

    outcomes = installer.uninstall_source_desktop_apps(
        _candidate_paths=(owned_system, owned_user, foreign, packaged),
    )

    assert outcomes == ("removed", "removed", "foreign-source", "packaged")
    assert not owned_system.exists()
    assert not owned_user.exists()
    assert foreign.exists()
    assert asar.read_bytes() == b"packaged"


def test_uninstall_source_app_rechecks_ownership_under_lock(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    target = tmp_path / "Applications" / "vibe-view.app"
    generated = _make_source_bundle(target.parent)
    generated.rename(target)

    class SimulatedRace:
        def __enter__(self):
            installer._remove_path(target)
            replacement = _make_source_bundle(
                target.parent,
                checkout=tmp_path / "other-checkout",
            )
            replacement.rename(target)

        def __exit__(self, *_args):
            return False

    monkeypatch.setattr(
        installer,
        "desktop_install_lock",
        lambda _destination: SimulatedRace(),
    )

    outcomes = installer.uninstall_source_desktop_apps(
        _candidate_paths=(target,),
    )

    assert outcomes == ("changed",)
    assert target.exists()
    assert installer.source_app_checkout(target) == (tmp_path / "other-checkout").resolve()


def test_uninstall_source_app_dry_run_is_non_destructive(
    mac_installer,
    tmp_path: Path,
) -> None:
    installer = mac_installer
    target = tmp_path / "Applications" / "vibe-view.app"
    generated = _make_source_bundle(target.parent)
    generated.rename(target)

    outcomes = installer.uninstall_source_desktop_apps(
        dry_run=True,
        _candidate_paths=(target,),
    )

    assert outcomes == ("would-remove",)
    assert target.exists()


def test_uninstall_empty_desktop_candidate_set_touches_no_applications_path(
    mac_installer,
    monkeypatch,
) -> None:
    installer = mac_installer

    def unexpected_classification(_candidate: Path) -> str:
        raise AssertionError("an explicit empty candidate set must stay empty")

    monkeypatch.setattr(installer, "desktop_app_kind", unexpected_classification)

    assert installer.uninstall_source_desktop_apps(_candidate_paths=()) == ()
    assert installer._choose_desktop_app_target(_candidate_paths=()) == (None, "missing")


def test_uninstall_removes_only_recognized_direct_download_runtime(
    installer,
    tmp_path: Path,
) -> None:
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")
    (runtime / ".vibe-view-install.lock").write_text("")

    assert installer.electron_runtime_kind(runtime) == "direct-download"
    assert installer.uninstall_electron_runtime(str(runtime), dry_run=True) == "would-remove"
    assert runtime.exists()
    assert installer.uninstall_electron_runtime(str(runtime)) == "removed"
    assert not runtime.exists()
    assert (runtime.parent / ".vibe-view-electron-install.lock").exists()


@pytest.mark.parametrize("kind", ("npm", "unknown", "symlink"))
def test_uninstall_preserves_unowned_electron_paths(
    installer,
    tmp_path: Path,
    kind: str,
) -> None:
    runtime = tmp_path / "electron"
    if kind == "symlink":
        destination = tmp_path / "foreign-electron"
        destination.mkdir()
        runtime.symlink_to(destination, target_is_directory=True)
    else:
        runtime.mkdir()
        if kind == "npm":
            (runtime / "package.json").write_text('{"name": "electron"}\n')
            (runtime / "vibe-view-electron-version").write_text("33.4.11\n")

    outcome = installer.uninstall_electron_runtime(str(runtime))

    assert outcome in {"npm-managed", "unknown"}
    assert runtime.exists() or runtime.is_symlink()


def test_uninstall_refuses_runtime_beneath_symlink_parent(
    installer,
    tmp_path: Path,
) -> None:
    real_parent = tmp_path / "real-node-modules"
    runtime = _make_direct_download_runtime(installer, real_parent / "electron")
    linked_parent = tmp_path / "node_modules"
    linked_parent.symlink_to(real_parent, target_is_directory=True)
    linked_runtime = linked_parent / "electron"

    assert installer.electron_runtime_kind(linked_runtime) == "unknown"
    assert installer.uninstall_electron_runtime(str(linked_runtime)) == "unknown"
    assert runtime.exists()


def test_install_refuses_usable_runtime_through_leaf_symlink(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    external = _make_direct_download_runtime(installer, tmp_path / "external-electron")
    sentinel = external / "index.js"
    before = sentinel.read_text()
    linked = tmp_path / "node_modules" / "electron"
    linked.parent.mkdir()
    linked.symlink_to(external, target_is_directory=True)
    monkeypatch.setattr(installer, "electron_runtime_is_usable", lambda *_args: True)

    with pytest.raises(RuntimeError, match="symlinked Electron target"):
        installer.install_electron("33.4.11", target_dir=str(linked))

    assert linked.is_symlink()
    assert sentinel.read_text() == before


@pytest.mark.parametrize(
    "name",
    (
        "package.json",
        "vibe-view-electron-version",
        "path.txt",
        "index.js",
        "cli.js",
    ),
)
@pytest.mark.parametrize("dangling", (False, True))
def test_uninstall_rejects_symlinked_or_dangling_runtime_metadata(
    installer,
    tmp_path: Path,
    name: str,
    dangling: bool,
) -> None:
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")
    path = runtime / name
    if path.exists():
        payload = path.read_text()
        path.unlink()
    else:
        payload = '{"name": "electron"}\n'
    external = tmp_path / f"external-{name}"
    if not dangling:
        external.write_text(payload)
    path.symlink_to(external)

    assert installer.electron_runtime_kind(runtime) == "unknown"
    assert installer.uninstall_electron_runtime(str(runtime)) == "unknown"
    assert runtime.is_dir()
    assert path.is_symlink()
    if not dangling:
        assert external.read_text() == payload


def test_uninstall_rejects_symlinked_dist_and_legacy_lock(
    installer,
    tmp_path: Path,
) -> None:
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")
    external_dist = tmp_path / "external-dist"
    external_dist.mkdir()
    (runtime / "dist").rmdir()
    (runtime / "dist").symlink_to(external_dist, target_is_directory=True)

    assert installer.electron_runtime_kind(runtime) == "unknown"
    assert installer.uninstall_electron_runtime(str(runtime)) == "unknown"
    assert external_dist.exists()

    (runtime / "dist").unlink()
    (runtime / "dist").mkdir()
    external_lock = tmp_path / "external-lock"
    external_lock.write_text("keep\n")
    (runtime / ".vibe-view-install.lock").symlink_to(external_lock)

    assert installer.electron_runtime_kind(runtime) == "unknown"
    assert installer.uninstall_electron_runtime(str(runtime)) == "unknown"
    assert external_lock.read_text() == "keep\n"


@pytest.mark.parametrize(
    "record",
    ("", "33.4\n", "v33.4.11\n", "33.4.11\nextra\n", "not-a-version\n"),
)
def test_uninstall_rejects_invalid_version_record(
    installer,
    tmp_path: Path,
    record: str,
) -> None:
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")
    (runtime / "vibe-view-electron-version").write_text(record)

    assert installer.electron_runtime_kind(runtime) == "unknown"
    assert installer.uninstall_electron_runtime(str(runtime)) == "unknown"
    assert runtime.exists()


@pytest.mark.parametrize("mutation", ("wrapper", "unknown-entry"))
def test_uninstall_requires_exact_wrappers_and_no_unknown_root_entries(
    installer,
    tmp_path: Path,
    mutation: str,
) -> None:
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")
    if mutation == "wrapper":
        (runtime / "index.js").write_text("module.exports = 'foreign';\n")
    else:
        (runtime / "keep-me").write_text("unknown owner\n")

    assert installer.electron_runtime_kind(runtime) == "unknown"
    assert installer.uninstall_electron_runtime(str(runtime)) == "unknown"
    assert runtime.exists()


def test_uninstall_runtime_rechecks_full_classifier_under_parent_lock(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")

    class SimulatedRace:
        def __enter__(self):
            (runtime / "package.json").write_text('{"name": "electron"}\n')

        def __exit__(self, *_args):
            return False

    monkeypatch.setattr(
        installer,
        "electron_install_lock",
        lambda _target: SimulatedRace(),
    )

    assert installer.uninstall_electron_runtime(str(runtime)) == "changed"
    assert (runtime / "package.json").exists()


def test_combined_uninstall_uses_runtime_then_app_lock_without_nesting(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    runtime = _make_direct_download_runtime(installer, tmp_path / "electron")
    app = tmp_path / "Applications" / "vibe-view.app"
    generated = _make_source_bundle(app.parent)
    generated.rename(app)
    events: list[str] = []

    class LoggedLock:
        def __init__(self, name: str):
            self.name = name

        def __enter__(self):
            events.append(f"enter-{self.name}")

        def __exit__(self, *_args):
            events.append(f"exit-{self.name}")
            return False

    monkeypatch.setattr(
        installer,
        "electron_install_lock",
        lambda _target: LoggedLock("runtime"),
    )
    monkeypatch.setattr(
        installer,
        "desktop_install_lock",
        lambda _target: LoggedLock("app"),
    )

    installer.uninstall_electron(
        str(runtime),
        _candidate_paths=(app,),
    )

    assert events == ["enter-runtime", "enter-app", "exit-app", "exit-runtime"]
    assert not runtime.exists()
    assert not app.exists()


def test_combined_uninstall_dry_run_does_not_create_or_take_runtime_lock(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    runtime = tmp_path / "missing-parent" / "electron"

    def unexpected_lock(_target: Path):
        raise AssertionError("dry-run must not create or take a persistent lock")

    monkeypatch.setattr(installer, "electron_install_lock", unexpected_lock)

    installer.uninstall_electron(
        str(runtime),
        dry_run=True,
        _candidate_paths=(),
    )

    assert not runtime.parent.exists()


def test_direct_uninstall_cli_refuses_sudo_even_in_ci(
    installer,
    monkeypatch,
    capsys,
) -> None:
    monkeypatch.setattr(installer.os, "name", "posix")
    monkeypatch.setattr(installer.os, "geteuid", lambda: 0, raising=False)
    monkeypatch.setenv("SUDO_USER", "regular-user")
    monkeypatch.setenv("CI", "true")
    monkeypatch.setenv("GITLAB_CI", "true")

    def unexpected_uninstall(**_kwargs):
        raise AssertionError("elevated uninstall must stop before mutation")

    monkeypatch.setattr(installer, "uninstall_electron", unexpected_uninstall)

    assert installer.main(["--uninstall", "--dry-run"]) == 2
    assert "Refusing to uninstall Electron as root or through sudo" in capsys.readouterr().err


def test_direct_uninstall_cli_refuses_root_outside_gitlab_ci(
    installer,
    monkeypatch,
    capsys,
) -> None:
    monkeypatch.setattr(installer.os, "name", "posix")
    monkeypatch.setattr(installer.os, "geteuid", lambda: 0, raising=False)
    monkeypatch.delenv("SUDO_USER", raising=False)
    monkeypatch.delenv("CI", raising=False)
    monkeypatch.delenv("GITLAB_CI", raising=False)

    def unexpected_uninstall(**_kwargs):
        raise AssertionError("interactive root uninstall must stop before mutation")

    monkeypatch.setattr(installer, "uninstall_electron", unexpected_uninstall)

    assert installer.main(["--uninstall", "--dry-run"]) == 2
    assert "Refusing to uninstall Electron as root or through sudo" in capsys.readouterr().err


def test_direct_uninstall_cli_allows_gitlab_root_runner(
    installer,
    monkeypatch,
) -> None:
    monkeypatch.setattr(installer.os, "name", "posix")
    monkeypatch.setattr(installer.os, "geteuid", lambda: 0, raising=False)
    monkeypatch.delenv("SUDO_USER", raising=False)
    monkeypatch.setenv("CI", "true")
    monkeypatch.setenv("GITLAB_CI", "true")
    calls: list[bool] = []
    monkeypatch.setattr(
        installer,
        "uninstall_electron",
        lambda *, dry_run: calls.append(dry_run),
    )

    assert installer.main(["--uninstall", "--dry-run"]) == 0
    assert calls == [True]


def test_direct_uninstall_cli_allows_regular_posix_user(
    installer,
    monkeypatch,
) -> None:
    monkeypatch.setattr(installer.os, "name", "posix")
    monkeypatch.setattr(installer.os, "geteuid", lambda: 501, raising=False)
    monkeypatch.delenv("SUDO_USER", raising=False)
    calls: list[bool] = []
    monkeypatch.setattr(
        installer,
        "uninstall_electron",
        lambda *, dry_run: calls.append(dry_run),
    )

    assert installer.main(["--uninstall", "--dry-run"]) == 0
    assert calls == [True]


def test_staging_failure_preserves_existing_source_app(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"
    _make_source_bundle(target.parent)
    generated = target.parent / "Electron.app"
    generated.rename(target)
    sentinel = target / "keep.txt"
    sentinel.write_text("old app\n")

    def fail_copy(*_args, **_kwargs):
        raise OSError("simulated copy failure")

    monkeypatch.setattr(installer.shutil, "copytree", fail_copy)
    with pytest.raises(OSError, match="simulated copy failure"):
        installer.install_desktop_app(source_dist, force=True, target_dir=target)

    assert sentinel.read_text() == "old app\n"


def test_codesign_failure_preserves_existing_source_app(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"
    _make_source_bundle(target.parent)
    generated = target.parent / "Electron.app"
    generated.rename(target)
    sentinel = target / "keep.txt"
    sentinel.write_text("old app\n")

    def fail_sign(*_args, **_kwargs):
        raise RuntimeError("codesign of staged desktop app failed: bad sign")

    monkeypatch.setattr(installer, "_sign_macos_app", fail_sign)

    with pytest.raises(RuntimeError, match="codesign"):
        installer.install_desktop_app(source_dist, force=True, target_dir=target)

    assert sentinel.read_text() == "old app\n"


def test_swap_failure_rolls_back_existing_source_app(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"
    _make_source_bundle(target.parent)
    generated = target.parent / "Electron.app"
    generated.rename(target)
    sentinel = target / "keep.txt"
    sentinel.write_text("old app\n")
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    real_replace = installer.os.replace
    calls = 0

    def fail_new_app_swap(source, destination):
        nonlocal calls
        calls += 1
        if calls == 2:
            raise OSError("simulated swap failure")
        return real_replace(source, destination)

    monkeypatch.setattr(installer.os, "replace", fail_new_app_swap)
    real_rmtree = installer.shutil.rmtree

    def fail_stage_cleanup(path, *args, **kwargs):
        if Path(path).name.startswith(".vibe-view-stage-"):
            raise OSError("simulated staging cleanup failure")
        return real_rmtree(path, *args, **kwargs)

    monkeypatch.setattr(installer.shutil, "rmtree", fail_stage_cleanup)
    with pytest.raises(OSError, match="simulated swap failure"):
        installer.install_desktop_app(source_dist, force=True, target_dir=target)

    assert sentinel.read_text() == "old app\n"


def test_branding_refreshes_vibe_view_version(installer, tmp_path: Path, monkeypatch) -> None:
    # brand_macos_app gates on sys.platform (7e565c3c8), so patch the same
    # attribute the mac_installer fixture patches; a platform.system patch
    # leaves the guard un-taken on the Linux CI image and the synthetic
    # plist never receives the version keys this test reads.
    monkeypatch.setattr(installer.sys, "platform", "darwin")
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    dist = tmp_path / "dist"
    app = _make_source_bundle(dist, version="old")

    installer.brand_macos_app(dist)

    with (app / "Contents" / "Info.plist").open("rb") as stream:
        plist = plistlib.load(stream)
    assert plist["CFBundleShortVersionString"] == installer.project_version()
    assert plist["CFBundleVersion"] == installer.project_version()


def test_branded_app_declares_document_types_for_open_with(
    mac_installer,
    tmp_path: Path,
) -> None:
    """The branded app must declare every importable format so macOS
    lists vibe-view in Finder's Open With menu for .py inputs and the
    loose structure formats, at Alternate rank (never stealing the
    default Python-file handler)."""
    installer = mac_installer
    dist = tmp_path / "dist"
    app = _make_source_bundle(dist, version="old")

    installer.brand_macos_app(dist)

    with (app / "Contents" / "Info.plist").open("rb") as stream:
        plist = plistlib.load(stream)
    types = plist.get("CFBundleDocumentTypes", [])
    extensions = {
        ext for entry in types for ext in entry.get("CFBundleTypeExtensions", [])
    }
    assert {
        "py", "qvf", "xyz", "cif", "cube", "pdb", "mol2", "sdf", "mol",
        "gjf", "com", "gro",
    } <= extensions
    assert all(entry.get("LSHandlerRank") == "Alternate" for entry in types)
    assert all(entry.get("CFBundleTypeRole") == "Viewer" for entry in types)
    utis = plist.get("UTImportedTypeDeclarations", [])
    assert any(u.get("UTTypeIdentifier") == "com.vibeqc.vibeview.py" for u in utis)


def test_checksum_mismatch_is_rejected(installer, tmp_path: Path, monkeypatch) -> None:
    archive = tmp_path / "electron.zip"
    archive.write_bytes(b"not the release archive")

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self):
            return b"0" * 64 + b"  electron.zip\n"

    monkeypatch.setattr(
        installer.urllib.request,
        "urlopen",
        lambda _req, **_kwargs: Response(),
    )

    with pytest.raises(RuntimeError, match="checksum mismatch"):
        installer.verify_download_checksum(archive, "33.4.11", "electron.zip")


def test_checksum_success_uses_bounded_request(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    import hashlib

    archive = tmp_path / "electron.zip"
    archive.write_bytes(b"release archive")
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    timeouts: list[int] = []

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self):
            return f"{digest} *electron.zip\n".encode()

    def urlopen(_req, *, timeout: int):
        timeouts.append(timeout)
        return Response()

    monkeypatch.setattr(installer.urllib.request, "urlopen", urlopen)

    installer.verify_download_checksum(archive, "33.4.11", "electron.zip")

    assert timeouts == [installer.NETWORK_TIMEOUT_SECONDS]


def test_checksum_manifest_must_name_archive(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    archive = tmp_path / "electron.zip"
    archive.write_bytes(b"release archive")

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self):
            return b"0" * 64 + b" *some-other.zip\n"

    monkeypatch.setattr(
        installer.urllib.request,
        "urlopen",
        lambda _req, **_kwargs: Response(),
    )

    with pytest.raises(RuntimeError, match="checksum not found"):
        installer.verify_download_checksum(archive, "33.4.11", "electron.zip")


def _dock_prefs_with_tile(prefs: Path, url: str) -> None:
    tile = {
        "tile-data": {
            "file-data": {"_CFURLString": url, "_CFURLStringType": 15},
            "file-label": "vibe-view",
            "file-type": 41,
        },
        "tile-type": "file-tile",
    }
    with prefs.open("wb") as stream:
        plistlib.dump({"persistent-apps": [tile]}, stream)


class _FakeCompleted:
    def __init__(self, returncode: int = 0):
        self.returncode = returncode


def test_pin_to_dock_appends_tile_and_reloads(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    app = tmp_path / "Applications" / "vibe-view.app"
    app.mkdir(parents=True)
    prefs = tmp_path / "home" / "Library" / "Preferences" / "com.apple.dock.plist"
    reloads: list[list[str]] = []

    def run(command, **_kwargs):
        reloads.append(command)
        return _FakeCompleted(0)

    monkeypatch.setattr(installer.subprocess, "run", run)

    assert installer.pin_to_dock(app, _prefs_path=prefs) == "pinned"
    with prefs.open("rb") as stream:
        dock = plistlib.load(stream)
    assert len(dock["persistent-apps"]) == 1
    assert (
        dock["persistent-apps"][0]["tile-data"]["file-data"]["_CFURLString"]
        == app.resolve().as_uri() + "/"
    )
    assert reloads == [["killall", "Dock"]]


def test_pin_to_dock_is_idempotent(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    app = tmp_path / "Applications" / "vibe-view.app"
    app.mkdir(parents=True)
    prefs = tmp_path / "com.apple.dock.plist"
    _dock_prefs_with_tile(prefs, app.resolve().as_uri() + "/")
    monkeypatch.setattr(installer.subprocess, "run", lambda *_a, **_k: None)

    assert installer.pin_to_dock(app, _prefs_path=prefs) == "already-pinned"
    with prefs.open("rb") as stream:
        dock = plistlib.load(stream)
    assert len(dock["persistent-apps"]) == 1


def test_pin_to_dock_is_not_applicable_off_macos(
    installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setattr(installer.sys, "platform", "linux")
    app = tmp_path / "vibe-view.app"

    assert installer.pin_to_dock(app) == "not-applicable"


def test_unpin_from_dock_removes_only_matching_tiles(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    app = tmp_path / "vibe-view.app"
    app.mkdir(parents=True)
    other_app = tmp_path / "Other.app"
    other_app.mkdir(parents=True)
    prefs = tmp_path / "com.apple.dock.plist"
    _dock_prefs_with_tile(prefs, app.resolve().as_uri() + "/")
    with prefs.open("rb") as stream:
        dock = plistlib.load(stream)
    dock["persistent-apps"].append(
        {
            "tile-data": {
                "file-data": {
                    "_CFURLString": other_app.resolve().as_uri() + "/",
                    "_CFURLStringType": 15,
                },
                "file-label": "Other",
                "file-type": 41,
            },
            "tile-type": "file-tile",
        }
    )
    with prefs.open("wb") as stream:
        plistlib.dump(dock, stream)
    monkeypatch.setattr(
        installer.subprocess,
        "run",
        lambda *_a, **_k: _FakeCompleted(0),
    )

    assert installer.unpin_from_dock(app, _prefs_path=prefs) == "unpinned"
    with prefs.open("rb") as stream:
        remaining = plistlib.load(stream)
    assert len(remaining["persistent-apps"]) == 1
    assert (
        remaining["persistent-apps"][0]["tile-data"]["file-data"]["_CFURLString"]
        == other_app.resolve().as_uri() + "/"
    )


def test_unpin_from_dock_dry_run_reports_without_writing(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    app = tmp_path / "vibe-view.app"
    app.mkdir(parents=True)
    prefs = tmp_path / "com.apple.dock.plist"
    _dock_prefs_with_tile(prefs, app.resolve().as_uri() + "/")
    monkeypatch.setattr(
        installer.subprocess,
        "run",
        lambda *_a, **_k: _FakeCompleted(0),
    )

    assert (
        installer.unpin_from_dock(app, dry_run=True, _prefs_path=prefs)
        == "would-unpin"
    )
    with prefs.open("rb") as stream:
        dock = plistlib.load(stream)
    assert len(dock["persistent-apps"]) == 1


def test_desktop_app_install_pins_dock_when_requested(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    pins: list[Path] = []
    monkeypatch.setattr(
        installer,
        "pin_to_dock",
        lambda bundle, **_kwargs: pins.append(bundle) or "pinned",
    )
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"

    status = installer.install_desktop_app(
        source_dist,
        target_dir=target,
        pin_dock=True,
    )

    assert status == "installed"
    assert pins == [target]


def test_desktop_app_install_skips_dock_by_default(
    mac_installer,
    tmp_path: Path,
    monkeypatch,
) -> None:
    installer = mac_installer
    monkeypatch.setattr(installer.shutil, "which", lambda _name: None)
    pins: list[Path] = []
    monkeypatch.setattr(
        installer,
        "pin_to_dock",
        lambda bundle, **_kwargs: pins.append(bundle) or "pinned",
    )
    source_dist = tmp_path / "runtime" / "dist"
    _make_source_bundle(source_dist)
    target = tmp_path / "Applications" / "vibe-view.app"

    installer.install_desktop_app(source_dist, target_dir=target)

    assert pins == []


def test_cli_dock_flag_forwards_pin_request(installer, monkeypatch) -> None:
    calls: list[dict] = []

    def fake_install_electron(*_args, **kwargs):
        calls.append(kwargs)
        return "installed"

    monkeypatch.setattr(installer, "install_electron", fake_install_electron)

    assert installer.main(["--dock"]) == 0
    assert calls == [{"pin_dock": True, "refresh_app": False, "adopt_app": False}]


@pytest.mark.parametrize(
    "args",
    (
        ("--dock", "--check"),
        ("--check", "--dock"),
        ("--uninstall", "--dock"),
    ),
)
def test_cli_rejects_dock_with_check_or_uninstall(
    installer,
    monkeypatch,
    args: tuple[str, ...],
) -> None:
    monkeypatch.setattr(
        installer,
        "install_electron",
        lambda *_args, **_kwargs: "installed",
    )

    with pytest.raises(SystemExit) as excinfo:
        installer.main(list(args))
    assert excinfo.value.code == 2
