#!/usr/bin/env python3
"""Download and install Electron directly from GitHub releases.

Usage:
    python3 install-electron.py          # install reviewed project version
    python3 install-electron.py 43.3.0   # install specific version
    python3 install-electron.py --uninstall  # remove this checkout's runtime/app
"""

import argparse
import hashlib
import json
import os
import platform
import plistlib
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.request
import zipfile
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

SOURCE_APP_MARKER = "vibe-view-source-app.json"
SOURCE_DESKTOP_UPDATE_PROTOCOL = 1
NETWORK_TIMEOUT_SECONDS = 60
_ELECTRON_VERSION_RECORD_RE = re.compile(r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?\n\Z")


def project_version() -> str:
    """Return the vibe-view version used by the desktop source bundle."""
    package_json = Path(__file__).parent / "package.json"
    return str(json.loads(package_json.read_text())["version"])


def _source_app_marker(app_bundle: Path) -> Path:
    return app_bundle / "Contents" / "Resources" / "app" / SOURCE_APP_MARKER


def _launcher_checkout(app_bundle: Path) -> Path | None:
    """Return the checkout encoded by an exact generated launcher."""
    launcher = app_bundle / "Contents" / "Resources" / "app" / "launcher.js"
    if launcher.is_symlink() or not launcher.is_file():
        return None
    try:
        lines = launcher.read_text().splitlines()
    except (OSError, UnicodeError):
        return None
    required_preamble = [
        "// Generated by install-electron.py -- Dock/double-click launcher.",
        "// Loads the real vibe-view app from the source checkout that ran",
        "// the installer; re-run install-electron.py if the checkout moves.",
    ]
    if lines[:3] != required_preamble:
        return None
    body = lines[3:]
    if body and body[0].startswith("// vibe-view "):
        body = body[1:]
    if len(body) != 1 or not body[0].startswith("require(") or not body[0].endswith(");"):
        return None
    try:
        raw_main_js = Path(json.loads(body[0][len("require(") : -2]))
    except (json.JSONDecodeError, TypeError, ValueError):
        return None
    if not raw_main_js.is_absolute():
        return None
    main_js = raw_main_js.resolve()
    if main_js.name != "main.js" or main_js.parent.name != "electron":
        return None
    return main_js.parent.parent.resolve()


def source_app_checkout(app_bundle: Path) -> Path | None:
    """Return the checkout owning a valid marked or legacy source app."""
    launcher_checkout = _launcher_checkout(app_bundle)
    marker = _source_app_marker(app_bundle)
    if marker.is_symlink():
        return None
    if not marker.exists():
        return launcher_checkout
    if not marker.is_file():
        return None

    try:
        payload = json.loads(marker.read_text())
        raw_checkout = Path(payload["checkout"])
        if (
            payload.get("schema") != SOURCE_DESKTOP_UPDATE_PROTOCOL
            or payload.get("kind") != "vibe-view-source-desktop"
            or not raw_checkout.is_absolute()
        ):
            return None
        marker_checkout = raw_checkout.resolve()
    except (OSError, UnicodeError, KeyError, TypeError, ValueError):
        return None
    if launcher_checkout != marker_checkout:
        return None
    return marker_checkout


def desktop_app_kind(app_bundle: Path) -> str:
    """Classify a macOS app without confusing source and packaged builds."""
    if app_bundle.is_symlink():
        return "unknown"
    if not app_bundle.exists():
        return "missing"
    resources = app_bundle / "Contents" / "Resources"
    if (resources / "app.asar").exists() or (resources / "app-update.yml").exists():
        return "packaged"
    if source_app_checkout(app_bundle) is not None:
        return "source"
    return "unknown"


def configured_electron_version() -> str:
    """Return the exact Electron version reviewed in package-lock.json."""
    lock_path = Path(__file__).parent / "package-lock.json"
    lock = json.loads(lock_path.read_text())
    return str(lock["packages"]["node_modules/electron"]["version"])


def get_download_url(version: str) -> str:
    """Build the download URL for the current platform."""
    system = platform.system().lower()
    machine = platform.machine().lower()
    if machine in ("arm64", "aarch64"):
        arch = "arm64"
    elif machine in ("x86_64", "amd64", "x64"):
        arch = "x64"
    else:
        raise RuntimeError(f"Unsupported Electron architecture: {machine}")

    if system == "darwin":
        return f"https://github.com/electron/electron/releases/download/v{version}/electron-v{version}-darwin-{arch}.zip"
    if system == "linux":
        return f"https://github.com/electron/electron/releases/download/v{version}/electron-v{version}-linux-{arch}.zip"
    if system == "windows":
        return f"https://github.com/electron/electron/releases/download/v{version}/electron-v{version}-win32-{arch}.zip"
    raise RuntimeError(f"Unsupported platform: {system}")


def verify_download_checksum(zip_path: Path, version: str, filename: str) -> None:
    """Verify an Electron archive against the release's SHA256 manifest."""
    sums_url = f"https://github.com/electron/electron/releases/download/v{version}/SHASUMS256.txt"
    req = urllib.request.Request(sums_url, headers={"User-Agent": "vibe-view"})
    with urllib.request.urlopen(req, timeout=NETWORK_TIMEOUT_SECONDS) as resp:
        manifest = resp.read().decode("utf-8")

    expected = None
    for line in manifest.splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) == 2 and parts[1].lstrip("*") == filename:
            expected = parts[0].lower()
            break
    if expected is None:
        raise RuntimeError(f"Electron checksum not found for {filename}")

    digest = hashlib.sha256()
    with zip_path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    actual = digest.hexdigest().lower()
    if actual != expected:
        raise RuntimeError(
            f"Electron checksum mismatch for {filename}: expected {expected}, got {actual}"
        )
    print("Electron archive checksum verified.")


def _binary_relpath() -> str:
    """Relative path of the Electron executable inside dist/."""
    system = platform.system().lower()
    if system == "darwin":
        return "Electron.app/Contents/MacOS/Electron"
    if system == "windows":
        return "electron.exe"
    return "electron"


def _electron_binary_probe(binary: Path) -> tuple[str, str]:
    """Return Electron's engine version and a bounded failure diagnostic."""
    env = dict(os.environ)
    env["ELECTRON_RUN_AS_NODE"] = "1"
    command = [str(binary), "-p", "process.versions.electron"]
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=15,
            env=env,
        )
    except OSError as exc:
        return "unknown", str(exc)
    except subprocess.TimeoutExpired:
        return "unknown", "Electron version probe timed out"
    except subprocess.SubprocessError as exc:
        return "unknown", str(exc)
    output = f"{result.stdout}\n{result.stderr}".strip()
    diagnostic = " ".join(output.splitlines())[-1000:]
    if result.returncode != 0:
        return "unknown", diagnostic or f"Electron exited with status {result.returncode}"
    match = re.search(
        r"\bv?(\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?)\b",
        output,
    )
    if match:
        return match.group(1), diagnostic
    return "unknown", diagnostic or "Electron did not report an engine version"


def electron_binary_version(binary: Path) -> str:
    """Return Electron's engine version without launching its bundled app."""
    return _electron_binary_probe(binary)[0]


def electron_runtime_version(dist_dir: Path, *, include_recorded: bool = True) -> str:
    """Read the Electron engine version without using app display metadata."""
    recorded = dist_dir.parent / "vibe-view-electron-version"
    if include_recorded and recorded.exists():
        try:
            value = recorded.read_text().strip().lstrip("v")
            if value:
                return value
        except (OSError, UnicodeError):
            pass

    version_file = dist_dir / "version"
    if version_file.exists():
        try:
            value = version_file.read_text().strip().lstrip("v")
            if value:
                return value
        except (OSError, UnicodeError):
            pass

    framework_plist = (
        dist_dir
        / "Electron.app"
        / "Contents"
        / "Frameworks"
        / "Electron Framework.framework"
        / "Versions"
        / "A"
        / "Resources"
        / "Info.plist"
    )
    if framework_plist.exists():
        import plistlib

        try:
            with framework_plist.open("rb") as stream:
                plist = plistlib.load(stream)
            value = str(plist.get("CFBundleShortVersionString", "")).lstrip("v")
            if value:
                return value
        except (OSError, plistlib.InvalidFileException, ValueError):
            pass

    binary = dist_dir / _binary_relpath()
    if binary.exists():
        return electron_binary_version(binary)
    return "unknown"


def electron_runtime_is_usable(dist_dir: Path, expected_version: str) -> bool:
    """Return whether an installed runtime is executable and at the right pin."""
    binary = dist_dir / _binary_relpath()
    if not binary.is_file():
        return False
    if platform.system().lower() != "windows" and not os.access(binary, os.X_OK):
        return False
    return electron_binary_version(binary) == expected_version


def electron_runtime_health(dist_dir: Path, expected_version: str) -> tuple[str, str]:
    """Classify a runtime as healthy, repairable, or missing Linux libraries."""
    binary = dist_dir / _binary_relpath()
    if not binary.is_file():
        return "repair", "Electron executable is missing"
    if platform.system().lower() != "windows" and not os.access(binary, os.X_OK):
        return "repair", "Electron executable is not executable"

    detected, diagnostic = _electron_binary_probe(binary)
    if detected == expected_version:
        return "healthy", diagnostic

    recorded = electron_runtime_version(dist_dir)
    missing_library_markers = (
        "error while loading shared libraries",
        "cannot open shared object file",
    )
    if (
        platform.system().lower() == "linux"
        and recorded == expected_version
        and any(marker in diagnostic.lower() for marker in missing_library_markers)
    ):
        return "platform-dependency", diagnostic
    return "repair", diagnostic


@contextmanager
def _exclusive_file_lock(lock_path: Path) -> Iterator[None]:
    """Hold an advisory cross-process lock for one mutation target."""
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+b") as stream:
        stream.seek(0)
        if os.name == "nt":
            import msvcrt

            if lock_path.stat().st_size == 0:
                stream.write(b"\0")
                stream.flush()
                stream.seek(0)
            msvcrt.locking(stream.fileno(), msvcrt.LK_LOCK, 1)
            try:
                yield
            finally:
                stream.seek(0)
                msvcrt.locking(stream.fileno(), msvcrt.LK_UNLCK, 1)
        else:
            import fcntl

            fcntl.flock(stream.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(stream.fileno(), fcntl.LOCK_UN)


def _path_has_symlink_component(path: Path) -> bool:
    """Return whether an absolute lexical path traverses any symlink."""
    absolute = Path(os.path.abspath(path))
    current = Path(absolute.anchor)
    for part in absolute.parts[1:]:
        current /= part
        if current.is_symlink():
            return True
    return False


@contextmanager
def electron_install_lock(target_dir: Path) -> Iterator[None]:
    """Serialize mutations through a lock that survives runtime deletion."""
    parent = target_dir.parent
    if _path_has_symlink_component(target_dir):
        raise RuntimeError(f"refusing symlinked Electron target: {target_dir}")
    parent.mkdir(parents=True, exist_ok=True)
    if _path_has_symlink_component(target_dir) or not parent.is_dir():
        raise RuntimeError(f"refusing unsafe Electron target parent: {parent}")
    with _exclusive_file_lock(parent / ".vibe-view-electron-install.lock"):
        yield


@contextmanager
def desktop_install_lock(destination: Path) -> Iterator[None]:
    """Serialize all checkouts that can replace one Applications bundle."""
    with _exclusive_file_lock(destination.parent / ".vibe-view-desktop-install.lock"):
        yield


def _sign_macos_app(
    app_dir: Path,
    *,
    strict: bool,
    verify: bool,
    context: str,
) -> None:
    """Ad-hoc sign a modified app bundle and optionally verify it."""
    codesign = shutil.which("codesign")
    if not codesign:
        message = f"codesign not found; {context} may not launch on arm64"
        if strict:
            raise RuntimeError(message)
        print(f"Warning: {message}.")
        return

    sign = subprocess.run(
        [codesign, "--force", "--deep", "--sign", "-", str(app_dir)],
        capture_output=True,
        text=True,
    )
    if sign.returncode != 0:
        message = f"codesign of {context} failed: {sign.stderr.strip()}"
        if strict:
            raise RuntimeError(message)
        print(f"Warning: {message}")
        return
    if not verify:
        return

    checked = subprocess.run(
        [codesign, "--verify", "--deep", "--strict", str(app_dir)],
        capture_output=True,
        text=True,
    )
    if checked.returncode != 0:
        raise RuntimeError(f"codesign verification of {context} failed: {checked.stderr.strip()}")


def _npm_wrapper_payloads() -> dict[str, str]:
    """Return the exact wrapper files owned by the direct-download installer."""
    return {
        "path.txt": _binary_relpath() + "\n",
        "index.js": (
            "const fs=require('fs'),path=require('path');"
            "module.exports=path.join(__dirname,'dist',"
            "fs.readFileSync(path.join(__dirname,'path.txt'),'utf8').trim());\n"
        ),
        "cli.js": (
            "const e=require('./index.js');"
            "require('child_process').spawn(e,process.argv.slice(2),{stdio:'inherit'})"
            ".on('exit',c=>process.exit(c));\n"
        ),
    }


def electron_runtime_kind(target_dir: Path) -> str:
    """Classify a direct-download runtime without following ownership links.

    The version record is only an ownership signal when the whole package root
    has the exact shape written by this installer.  npm packages and anything
    ambiguous are deliberately preserved.
    """
    target = Path(target_dir)
    if _path_has_symlink_component(target):
        return "unknown"
    if not target.exists():
        return "missing"
    if not target.is_dir():
        return "unknown"

    npm_manifest = target / "package.json"
    if npm_manifest.is_symlink():
        return "unknown"
    if npm_manifest.exists():
        return "npm-managed" if npm_manifest.is_file() else "unknown"

    wrappers = _npm_wrapper_payloads()
    required_names = {
        "dist",
        "vibe-view-electron-version",
        *wrappers,
    }
    allowed_names = required_names | {".vibe-view-install.lock"}
    try:
        entries = {entry.name: entry for entry in target.iterdir()}
    except OSError:
        return "unknown"
    if not required_names.issubset(entries) or not set(entries).issubset(allowed_names):
        return "unknown"

    dist_dir = entries["dist"]
    if dist_dir.is_symlink() or not dist_dir.is_dir():
        return "unknown"

    version_record = entries["vibe-view-electron-version"]
    if version_record.is_symlink() or not version_record.is_file():
        return "unknown"
    try:
        version_text = version_record.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return "unknown"
    if _ELECTRON_VERSION_RECORD_RE.fullmatch(version_text) is None:
        return "unknown"

    for name, expected in wrappers.items():
        wrapper = entries[name]
        if wrapper.is_symlink() or not wrapper.is_file():
            return "unknown"
        try:
            actual = wrapper.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            return "unknown"
        if actual != expected:
            return "unknown"

    legacy_lock = entries.get(".vibe-view-install.lock")
    if legacy_lock is not None and (legacy_lock.is_symlink() or not legacy_lock.is_file()):
        return "unknown"
    return "direct-download"


def write_npm_wrappers(target_dir: Path) -> None:
    """Write the minimal node_modules/electron wrapper files.

    ``npm start`` (package.json → ``node node_modules/electron/cli.js``)
    expects the electron npm package's entry points; these three files
    are the tiny subset it actually needs, so a GitHub-zip install
    behaves like an npm install.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    for name, payload in _npm_wrapper_payloads().items():
        (target_dir / name).write_text(payload)


def _document_type_declarations() -> tuple[list[dict], list[dict]]:
    """Build the macOS document-type declarations for the branded app.

    ``CFBundleDocumentTypes`` + ``UTImportedTypeDeclarations`` are what
    LaunchServices reads to list vibe-view in Finder's Open With menu and
    as a double-click candidate. Every format ``detect_format`` accepts is
    declared; the handler rank is Alternate so declaring .py never steals
    the default Python-file association.
    """
    extensions = {
        "qvf": "vibe-qc Visualization Archive",
        "py": "vibe-qc Python Input",
        "xyz": "XYZ Structure",
        "cif": "CIF Structure",
        "cube": "Gaussian Cube Volume",
        "pdb": "PDB Structure",
        "mol2": "Tripos Mol2 Structure",
        "sdf": "SDF Structure",
        "mol": "MDL Molfile",
        "gjf": "Gaussian Input",
        "com": "Gaussian Input",
        "gro": "GROMACS Structure",
    }
    imported_utis: list[dict] = []
    document_types: list[dict] = []
    for ext, description in extensions.items():
        uti = f"com.vibeqc.vibeview.{ext}"
        conforms = ["public.data"]
        if ext == "py":
            conforms = ["public.data", "public.source-code", "public.python-script"]
        imported_utis.append(
            {
                "UTTypeIdentifier": uti,
                "UTTypeDescription": description,
                "UTTypeConformsTo": conforms,
                "UTTypeTagSpecification": {"public.filename-extension": [ext]},
            }
        )
        document_types.append(
            {
                "CFBundleTypeName": description,
                "CFBundleTypeRole": "Viewer",
                "CFBundleTypeExtensions": [ext],
                "LSItemContentTypes": [uti],
                "LSHandlerRank": "Alternate",
            }
        )
    return document_types, imported_utis


def brand_macos_app(dist_dir: Path, *, sign: bool = True) -> None:
    """Rebrand the extracted Electron.app as vibe-view (macOS only).

    In dev mode (no packaged .app of our own) the dock and menu-bar
    names come from the bundle's Info.plist, not from app.setName() —
    so a stock download shows up as "Electron".  Rewrite CFBundleName /
    CFBundleDisplayName / CFBundleIdentifier, drop in our icon and
    document-type declarations, and ad-hoc re-sign (plist edits
    invalidate the original signature, and arm64 refuses to run
    unsigned binaries).  Idempotent.
    """
    if sys.platform != "darwin":
        return
    app_dir = dist_dir / "Electron.app"
    plist_path = app_dir / "Contents" / "Info.plist"
    if not plist_path.exists():
        return

    import plistlib

    with open(plist_path, "rb") as f:
        plist = plistlib.load(f)

    version = project_version()
    document_types, imported_utis = _document_type_declarations()
    desired = {
        "CFBundleName": "vibe-view",
        "CFBundleDisplayName": "vibe-view",
        "CFBundleIdentifier": "com.vibeqc.vibeview",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "CFBundleDocumentTypes": document_types,
        "UTImportedTypeDeclarations": imported_utis,
    }
    changed = any(plist.get(key) != value for key, value in desired.items())
    plist.update(desired)

    icns_src = Path(__file__).parent / "icon.icns"
    if icns_src.exists():
        icns_dest = app_dir / "Contents" / "Resources" / "vibeview.icns"
        if not icns_dest.exists() or icns_dest.read_bytes() != icns_src.read_bytes():
            shutil.copy(icns_src, icns_dest)
            changed = True
        if plist.get("CFBundleIconFile") != "vibeview.icns":
            changed = True
        plist["CFBundleIconFile"] = "vibeview.icns"

    if not changed:
        return

    print(f"Branding Electron.app as vibe-view {version}...")
    with open(plist_path, "wb") as f:
        plistlib.dump(plist, f)

    if sign:
        _sign_macos_app(
            app_dir,
            strict=False,
            verify=False,
            context="branded Electron.app",
        )


def write_launcher_shim(dist_dir: Path, *, sign: bool = True) -> None:
    """Make the branded Electron.app launch vibe-view on double-click (macOS).

    A stock Electron binary started with no arguments has no app to run, so a
    Dock / Finder double-click of the branded bundle exits silently; only the
    `vibe-view desktop` spawn path (`electron <app-dir>`) worked. Bake a tiny
    default app into Contents/Resources/app that requires the real main.js
    from the source checkout this installer ran from. Regenerated (and the
    bundle ad-hoc re-signed) whenever the target path changes, so a moved
    checkout just needs `python3 install-electron.py` again.
    """
    app_bundle = dist_dir / "Electron.app"
    if not app_bundle.exists():
        return  # non-macOS layout
    app_dir = app_bundle / "Contents" / "Resources" / "app"
    main_js = (Path(__file__).parent / "main.js").resolve()
    version = project_version()
    launcher = (
        "// Generated by install-electron.py -- Dock/double-click launcher.\n"
        "// Loads the real vibe-view app from the source checkout that ran\n"
        "// the installer; re-run install-electron.py if the checkout moves.\n"
        f"// vibe-view {version}\n"
        f"require({json.dumps(str(main_js))});\n"
    )
    package = (
        json.dumps(
            {
                "name": "vibe-view-launcher",
                "private": True,
                "version": version,
                "main": "launcher.js",
            },
            indent=2,
        )
        + "\n"
    )
    marker = (
        json.dumps(
            {
                "schema": SOURCE_DESKTOP_UPDATE_PROTOCOL,
                "kind": "vibe-view-source-desktop",
                "version": version,
                "electron_version": electron_runtime_version(dist_dir),
                "checkout": str(Path(__file__).parent.parent.resolve()),
            },
            indent=2,
        )
        + "\n"
    )
    launcher_path = app_dir / "launcher.js"
    package_path = app_dir / "package.json"
    marker_path = app_dir / SOURCE_APP_MARKER
    if (
        launcher_path.exists()
        and launcher_path.read_text() == launcher
        and package_path.exists()
        and package_path.read_text() == package
        and marker_path.exists()
        and marker_path.read_text() == marker
    ):
        return  # up to date -- keep the existing signature
    app_dir.mkdir(parents=True, exist_ok=True)
    package_path.write_text(package)
    launcher_path.write_text(launcher)
    marker_path.write_text(marker)
    if sign:
        _sign_macos_app(
            app_bundle,
            strict=False,
            verify=False,
            context="source launcher",
        )
    print(f"Double-click launcher -> {main_js}")


def prepare_staged_runtime(dist_dir: Path) -> None:
    """Apply source metadata to a staged runtime and verify its signature."""
    if platform.system().lower() != "darwin":
        return
    app_bundle = dist_dir / "Electron.app"
    if not app_bundle.exists():
        raise RuntimeError("staged Electron runtime is missing Electron.app")
    brand_macos_app(dist_dir, sign=False)
    write_launcher_shim(dist_dir, sign=False)
    _sign_macos_app(
        app_bundle,
        strict=True,
        verify=True,
        context="staged Electron runtime",
    )


def _remove_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.exists():
        shutil.rmtree(path)


def _extract_zip_preserving_permissions(zip_path: Path, destination: Path) -> None:
    """Safely extract a ZIP while retaining Unix modes and symlinks.

    ``ZipFile.extractall`` intentionally ignores Unix mode metadata. That is
    not sufficient for Electron's Linux archive: helpers such as
    ``chrome_crashpad_handler`` and ``chrome-sandbox`` must remain executable.
    The system ``unzip`` command preserves those modes, so this pure-Python
    fallback must provide the same contract on minimal Linux installations.
    """
    root = destination.resolve()
    with zipfile.ZipFile(zip_path, "r") as archive:
        for member in archive.infolist():
            name = member.filename
            if not name or "\\" in name or "\0" in name:
                raise RuntimeError(f"unsafe path in Electron archive: {name!r}")
            parts = tuple(part for part in name.split("/") if part not in {"", "."})
            if name.startswith("/") or ".." in parts:
                raise RuntimeError(f"unsafe path in Electron archive: {name!r}")

            target = destination.joinpath(*parts)
            try:
                target.resolve(strict=False).relative_to(root)
            except ValueError as exc:
                raise RuntimeError(f"unsafe path in Electron archive: {name!r}") from exc

            mode = member.external_attr >> 16
            if member.is_dir() or stat.S_ISDIR(mode):
                target.mkdir(parents=True, exist_ok=True)
                if mode:
                    target.chmod(stat.S_IMODE(mode))
                continue

            target.parent.mkdir(parents=True, exist_ok=True)
            if stat.S_ISLNK(mode):
                link_value = archive.read(member).decode("utf-8")
                link_path = Path(link_value)
                if link_path.is_absolute():
                    raise RuntimeError(
                        f"unsafe symlink in Electron archive: {name!r} -> {link_value!r}"
                    )
                try:
                    (target.parent / link_path).resolve(strict=False).relative_to(root)
                except ValueError as exc:
                    raise RuntimeError(
                        f"unsafe symlink in Electron archive: {name!r} -> {link_value!r}"
                    ) from exc
                target.symlink_to(link_value)
                continue
            if stat.S_IFMT(mode) not in {0, stat.S_IFREG}:
                raise RuntimeError(f"unsupported file type in Electron archive: {name!r}")

            with archive.open(member, "r") as source, target.open("wb") as output:
                shutil.copyfileobj(source, output)
            if mode:
                target.chmod(stat.S_IMODE(mode))


def swap_staged_runtime(
    target_dir: Path,
    staged_dist: Path,
    version: str,
    transaction_root: Path,
) -> None:
    """Atomically replace dist and its version record, rolling both back."""
    dist_dir = target_dir / "dist"
    version_record = target_dir / "vibe-view-electron-version"
    previous_record = version_record.read_bytes() if version_record.exists() else None
    staged_record = transaction_root / "staged-electron-version"
    staged_record.write_text(version + "\n")
    previous_dist = transaction_root / "previous-dist"
    if dist_dir.exists() or dist_dir.is_symlink():
        os.replace(dist_dir, previous_dist)
    try:
        os.replace(staged_dist, dist_dir)
        os.replace(staged_record, version_record)
    except Exception:
        _remove_path(dist_dir)
        if previous_dist.exists() or previous_dist.is_symlink():
            os.replace(previous_dist, dist_dir)
        if previous_record is None:
            version_record.unlink(missing_ok=True)
        else:
            restored_record = transaction_root / "restored-electron-version"
            restored_record.write_bytes(previous_record)
            os.replace(restored_record, version_record)
        raise
    _remove_path(previous_dist)


def _choose_desktop_app_target(
    target_dir: Path | None = None,
    *,
    adopt_app: bool = False,
    _candidate_paths: tuple[Path, Path] | None = None,
) -> tuple[Path | None, str]:
    """Choose a source-app target without colliding with a packaged app."""
    if target_dir is not None:
        return target_dir, desktop_app_kind(target_dir)

    candidates = (
        _candidate_paths
        if _candidate_paths is not None
        else (
            Path("/Applications/vibe-view.app"),
            Path.home() / "Applications/vibe-view.app",
        )
    )
    if not candidates:
        return None, "missing"
    classified = [(candidate, desktop_app_kind(candidate)) for candidate in candidates]
    current = Path(__file__).parent.parent.resolve()

    # An app owned by this checkout wins even when a protected or foreign app
    # exists in the other Applications directory.
    for candidate, kind in classified:
        if kind == "source" and source_app_checkout(candidate) == current:
            for sibling, sibling_kind in classified:
                if sibling != candidate and sibling_kind in {"packaged", "unknown"}:
                    print(f"{sibling_kind.title()} desktop app left untouched -> {sibling}")
            return candidate, kind

    for candidate, kind in classified:
        if kind == "source":
            owner = source_app_checkout(candidate)
            if adopt_app:
                print(f"Adopting source-backed desktop app -> {candidate}")
                return candidate, kind
            print(f"Source-backed desktop app left untouched -> {candidate}")
            print(f"It belongs to a different checkout: {owner}")
            return None, "foreign-source"

    for candidate, kind in classified:
        if kind == "packaged":
            print(f"Packaged desktop app left untouched -> {candidate}")
            print("Use its Check for Updates menu or install the current DMG.")
            return None, kind
        if kind == "unknown":
            print(f"Unknown desktop app left untouched -> {candidate}")
            print("Move it aside before installing the source-backed desktop app.")
            return None, kind

    if _candidate_paths is not None:
        return candidates[0], "missing"
    system_candidate, user_candidate = candidates
    if os.access(system_candidate.parent, os.W_OK):
        return system_candidate, "missing"
    return user_candidate, "missing"


def install_desktop_app(
    dist_dir: Path,
    *,
    force: bool = False,
    target_dir: Path | None = None,
    adopt_app: bool = False,
    pin_dock: bool = False,
    _destination_locked: bool = False,
) -> str:
    """Install a discoverable vibe-view.app into an Applications folder (macOS).

    The branded bundle lives at node_modules/electron/dist/Electron.app, which
    Spotlight never indexes and which makes a fragile Dock target. Copy it to
    ~/Applications/vibe-view.app (or /Applications when writable) so Cmd+Space
    finds it and it pins to the Dock like any app. The Electron framework is
    inside the copy, while its launcher shim requires main.js from this checkout
    by absolute path, so the installed app tracks live code edits.

    Idempotent: skips the ~200 MB copy when an install already carries the same
    source marker and launcher. A packaged electron-builder app is never
    overwritten; it owns a separate update-feed lifecycle.
    """
    app_bundle = dist_dir / "Electron.app"
    if sys.platform != "darwin" or not app_bundle.exists():
        return "not-applicable"  # other platforms launch via the CLI

    dest, kind = _choose_desktop_app_target(target_dir, adopt_app=adopt_app)
    if dest is None:
        return kind
    if not _destination_locked:
        dest.parent.mkdir(parents=True, exist_ok=True)
        with desktop_install_lock(dest):
            # Reclassify under the shared Applications lock. Two different
            # checkouts have different runtime locks but the same app target.
            return install_desktop_app(
                dist_dir,
                force=force,
                target_dir=dest,
                adopt_app=adopt_app,
                pin_dock=pin_dock,
                _destination_locked=True,
            )
    if kind == "packaged":
        print(f"Packaged desktop app left untouched -> {dest}")
        print("Use its Check for Updates menu or install the current DMG.")
        return kind
    if kind == "unknown":
        print(f"Unknown desktop app left untouched -> {dest}")
        print("Move it aside before installing the source-backed desktop app.")
        return kind
    if kind == "source":
        owner = source_app_checkout(dest)
        current = Path(__file__).parent.parent.resolve()
        if owner != current:
            if adopt_app:
                print(f"Adopting source-backed desktop app -> {dest}")
            else:
                print(f"Source-backed desktop app left untouched -> {dest}")
                print(f"It belongs to a different checkout: {owner}")
                return "foreign-source"
    dest.parent.mkdir(parents=True, exist_ok=True)

    shim = app_bundle / "Contents" / "Resources" / "app" / "launcher.js"
    dest_shim = dest / "Contents" / "Resources" / "app" / "launcher.js"
    marker = _source_app_marker(app_bundle)
    dest_marker = _source_app_marker(dest)
    if (
        not force
        and dest.exists()
        and shim.exists()
        and dest_shim.exists()
        and dest_shim.read_text() == shim.read_text()
        and marker.exists()
        and dest_marker.exists()
        and dest_marker.read_text() == marker.read_text()
    ):
        if pin_dock:
            pin_to_dock(dest)
        print(f"Desktop app already installed -> {dest}")
        return "current"

    stage_root = Path(tempfile.mkdtemp(prefix=".vibe-view-stage-", dir=str(dest.parent)))
    backup_root: Path | None = None
    staged = stage_root / dest.name
    backup: Path | None = None
    try:
        shutil.copytree(app_bundle, staged, symlinks=True)
        executable = staged / "Contents" / "MacOS" / "Electron"
        package_path = staged / "Contents" / "Resources" / "app" / "package.json"
        required = (
            executable,
            staged / "Contents" / "Info.plist",
            staged / "Contents" / "Resources" / "app" / "launcher.js",
            package_path,
            _source_app_marker(staged),
        )
        missing = [str(path) for path in required if not path.exists()]
        if missing:
            raise RuntimeError(
                "refusing incomplete desktop app replacement; missing: " + ", ".join(missing)
            )
        if not executable.is_file() or not os.access(executable, os.X_OK):
            raise RuntimeError("refusing desktop app with a non-executable binary")
        current = Path(__file__).parent.parent.resolve()
        if source_app_checkout(staged) != current:
            raise RuntimeError(
                "refusing desktop app whose marker and launcher do not own the current checkout"
            )
        try:
            package = json.loads(package_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            raise RuntimeError("refusing desktop app with invalid package.json") from exc
        if (
            package.get("name") != "vibe-view-launcher"
            or package.get("version") != project_version()
        ):
            raise RuntimeError("refusing desktop app with stale launcher metadata")

        _sign_macos_app(
            staged,
            strict=True,
            verify=True,
            context="staged desktop app",
        )

        if dest.exists() or dest.is_symlink():
            backup_root = Path(tempfile.mkdtemp(prefix=".vibe-view-backup-", dir=str(dest.parent)))
            backup = backup_root / dest.name
            os.replace(dest, backup)
        os.replace(staged, dest)
    finally:
        # Restore first. Cleanup must never strand the only good app in a
        # temporary backup directory.
        if backup is not None and backup.exists() and not dest.exists():
            os.replace(backup, dest)
        for temporary in (stage_root, backup_root):
            if temporary is None or not temporary.exists():
                continue
            try:
                shutil.rmtree(temporary)
            except OSError as exc:
                print(f"Warning: could not remove temporary path {temporary}: {exc}")

    if pin_dock:
        pin_to_dock(dest)
    print(f"Installed desktop app -> {dest} (Spotlight + Dock)")
    return "installed"


def _dock_prefs_path(prefs_path: Path | None = None) -> Path:
    """Return the Dock preference plist used for pin/unpin operations."""
    if prefs_path is not None:
        return prefs_path
    return Path.home() / "Library" / "Preferences" / "com.apple.dock.plist"


def _dock_tile_url(app_bundle: Path) -> str:
    """Return the file-data URL macOS records for a pinned app bundle."""
    return app_bundle.resolve().as_uri().rstrip("/") + "/"


def _dock_tile_matches(entry: object, url: str) -> bool:
    """Return whether one Dock plist entry pins the given bundle URL."""
    if not isinstance(entry, dict):
        return False
    tile_data = entry.get("tile-data")
    if not isinstance(tile_data, dict):
        return False
    file_data = tile_data.get("file-data")
    return isinstance(file_data, dict) and file_data.get("_CFURLString") == url


def _read_dock_prefs(prefs: Path) -> dict:
    """Load the Dock preference plist, tolerating a missing or blank file."""
    try:
        with prefs.open("rb") as stream:
            dock = plistlib.load(stream)
    except FileNotFoundError:
        return {}
    except (OSError, plistlib.InvalidFileException) as exc:
        raise RuntimeError(f"could not read Dock preferences {prefs}: {exc}") from exc
    return dock if isinstance(dock, dict) else {}


def _write_dock_prefs(prefs: Path, dock: dict) -> None:
    """Persist the Dock preference plist as binary data."""
    try:
        prefs.parent.mkdir(parents=True, exist_ok=True)
        with prefs.open("wb") as stream:
            plistlib.dump(dock, stream, fmt=plistlib.FMT_BINARY)
    except OSError as exc:
        raise RuntimeError(f"could not write Dock preferences {prefs}: {exc}") from exc


def _reload_dock() -> None:
    """Ask the running Dock to reload its preferences."""
    result = subprocess.run(["killall", "Dock"], capture_output=True, text=True)
    if result.returncode != 0:
        print(
            "Warning: could not ask the Dock to reload; log out and back in "
            "to see the icon."
        )


def pin_to_dock(
    app_bundle: Path,
    *,
    _prefs_path: Path | None = None,
) -> str:
    """Pin the app bundle as a persistent Dock tile (macOS, idempotent).

    Appends the standard file-tile entry macOS writes when an app is dragged
    onto the Dock, then asks the Dock to reload. An existing tile for the same
    bundle URL (in persistent-apps or recent-apps) is left alone. Returns
    "pinned", "already-pinned", or "not-applicable" off macOS.
    """
    if sys.platform != "darwin":
        return "not-applicable"
    prefs = _dock_prefs_path(_prefs_path)
    dock = _read_dock_prefs(prefs)
    url = _dock_tile_url(app_bundle)
    for key in ("persistent-apps", "recent-apps"):
        if any(_dock_tile_matches(entry, url) for entry in dock.get(key, []) or []):
            print(f"Already pinned in the Dock -> {app_bundle}")
            return "already-pinned"
    tile = {
        "tile-data": {
            "file-data": {"_CFURLString": url, "_CFURLStringType": 15},
            "file-label": app_bundle.stem,
            "file-type": 41,
        },
        "tile-type": "file-tile",
    }
    dock.setdefault("persistent-apps", []).append(tile)
    _write_dock_prefs(prefs, dock)
    _reload_dock()
    print(f"Pinned to Dock -> {app_bundle}")
    return "pinned"


def unpin_from_dock(
    app_bundle: Path,
    *,
    dry_run: bool = False,
    _prefs_path: Path | None = None,
) -> str:
    """Remove Dock tiles that point at the app bundle (macOS)."""
    if sys.platform != "darwin":
        return "not-applicable"
    prefs = _dock_prefs_path(_prefs_path)
    dock = _read_dock_prefs(prefs)
    url = _dock_tile_url(app_bundle)
    kept: dict[str, list] = {}
    removed = 0
    for key in ("persistent-apps", "recent-apps"):
        kept[key] = []
        for entry in dock.get(key, []) or []:
            if _dock_tile_matches(entry, url):
                removed += 1
            else:
                kept[key].append(entry)
    if removed == 0:
        return "not-pinned"
    if dry_run:
        print(f"Would unpin from the Dock -> {app_bundle}")
        return "would-unpin"
    for key, entries in kept.items():
        if entries:
            dock[key] = entries
        else:
            dock.pop(key, None)
    _write_dock_prefs(prefs, dock)
    _reload_dock()
    print(f"Unpinned from the Dock -> {app_bundle}")
    return "unpinned"


def uninstall_source_desktop_apps(
    *,
    dry_run: bool = False,
    _candidate_paths: tuple[Path, ...] | None = None,
) -> tuple[str, ...]:
    """Remove only macOS source apps whose launcher belongs to this checkout."""
    if sys.platform != "darwin":
        return ("not-applicable",)

    candidates = (
        _candidate_paths
        if _candidate_paths is not None
        else (
            Path("/Applications/vibe-view.app"),
            Path.home() / "Applications/vibe-view.app",
        )
    )
    current = Path(__file__).parent.parent.resolve()
    outcomes: list[str] = []

    for candidate in candidates:
        kind = desktop_app_kind(candidate)
        if kind == "missing":
            continue
        if kind == "packaged":
            print(f"Packaged desktop app left untouched -> {candidate}")
            outcomes.append("packaged")
            continue
        if kind == "unknown":
            print(f"Unknown desktop app left untouched -> {candidate}")
            outcomes.append("unknown")
            continue

        owner = source_app_checkout(candidate)
        if owner != current:
            print(f"Source-backed desktop app left untouched -> {candidate}")
            print(f"It belongs to a different checkout: {owner}")
            outcomes.append("foreign-source")
            continue
        if dry_run:
            print(f"Would remove source-backed desktop app -> {candidate}")
            try:
                unpin_from_dock(candidate, dry_run=True)
            except RuntimeError as exc:
                print(f"Warning: could not update the Dock during uninstall: {exc}")
            outcomes.append("would-remove")
            continue

        with desktop_install_lock(candidate):
            # Reclassify while holding the same cross-checkout lock used by
            # install/update. Never act on a bundle that changed while waiting.
            if desktop_app_kind(candidate) != "source" or source_app_checkout(candidate) != current:
                print(f"Desktop app changed during uninstall; left untouched -> {candidate}")
                outcomes.append("changed")
                continue
            _remove_path(candidate)
            try:
                unpin_from_dock(candidate)
            except RuntimeError as exc:
                print(f"Warning: could not update the Dock during uninstall: {exc}")
            print(f"Removed source-backed desktop app -> {candidate}")
            outcomes.append("removed")

    if not any(outcome in {"removed", "would-remove"} for outcome in outcomes):
        print("No source-backed macOS app owned by this checkout was found.")
    return tuple(outcomes)


def uninstall_electron_runtime(
    target_dir: str | None = None,
    *,
    dry_run: bool = False,
    _runtime_locked: bool = False,
) -> str:
    """Remove the recognizable direct-download runtime owned by this checkout."""
    if target_dir is None:
        target_dir = str(Path(__file__).parent / "node_modules" / "electron")
    target = Path(target_dir)
    kind = electron_runtime_kind(target)
    if kind == "missing":
        print(f"No checkout-owned Electron runtime found -> {target}")
        return "missing"
    if kind == "npm-managed":
        print(f"npm-managed Electron package left untouched -> {target}")
        return kind
    if kind != "direct-download":
        print(f"Unrecognized Electron runtime left untouched -> {target}")
        return "unknown"
    if dry_run:
        print(f"Would remove checkout-owned Electron runtime -> {target}")
        return "would-remove"

    def remove_while_locked() -> str:
        # Recheck under the runtime lock. An npm install or repair that won the
        # lock first changes classification and must remain untouched.
        if electron_runtime_kind(target) != "direct-download":
            print(f"Electron runtime changed during uninstall; left untouched -> {target}")
            return "changed"
        _remove_path(target)
        return "removed"

    if _runtime_locked:
        outcome = remove_while_locked()
    else:
        with electron_install_lock(target):
            outcome = remove_while_locked()
    if outcome != "removed":
        return outcome
    print(f"Removed checkout-owned Electron runtime -> {target}")
    return "removed"


def uninstall_electron(
    target_dir: str | None = None,
    *,
    dry_run: bool = False,
    _candidate_paths: tuple[Path, ...] | None = None,
) -> None:
    """Remove source desktop artifacts while preserving packages and user data."""
    if target_dir is None:
        target_dir = str(Path(__file__).parent / "node_modules" / "electron")
    target = Path(target_dir)
    if dry_run:
        # A preview must not create the stable lock file or its parent.
        uninstall_source_desktop_apps(
            dry_run=True,
            _candidate_paths=_candidate_paths,
        )
        uninstall_electron_runtime(target_dir, dry_run=True)
        return
    # Match install/update's global lock order: runtime first, Applications
    # bundle second. Holding the stable parent lock across both removals also
    # prevents a concurrent install from publishing a new app between them.
    with electron_install_lock(target):
        uninstall_source_desktop_apps(
            dry_run=dry_run,
            _candidate_paths=_candidate_paths,
        )
        uninstall_electron_runtime(
            target_dir,
            dry_run=dry_run,
            _runtime_locked=True,
        )


def finalize_electron_install(
    target_dir: Path,
    dist_dir: Path,
    *,
    refresh_app: bool,
    adopt_app: bool,
    pin_dock: bool = False,
) -> str:
    """Refresh wrappers and install a prepared runtime's desktop app copy."""
    write_npm_wrappers(target_dir)
    return install_desktop_app(
        dist_dir,
        force=refresh_app,
        adopt_app=adopt_app,
        pin_dock=pin_dock,
    )


def install_electron(
    version: str | None = None,
    target_dir: str | None = None,
    *,
    refresh_app: bool = False,
    adopt_app: bool = False,
    pin_dock: bool = False,
) -> str:
    """Synchronize Electron to the reviewed version and refresh desktop state."""
    if target_dir is None:
        target_dir = str(Path(__file__).parent / "node_modules" / "electron")
    target_path = Path(target_dir)
    expected_version = version or configured_electron_version()
    if version is None:
        print(f"Using reviewed Electron version {expected_version} from package-lock.json...")

    with electron_install_lock(target_path):
        if refresh_app and sys.platform == "darwin":
            desktop_target, desktop_kind = _choose_desktop_app_target(adopt_app=adopt_app)
            if desktop_target is None:
                print("Electron runtime left unchanged because desktop ownership was refused.")
                return desktop_kind

        dist_dir = target_path / "dist"
        if electron_runtime_is_usable(dist_dir, expected_version):
            print(f"Electron {expected_version} is already installed and valid")
            if platform.system().lower() == "darwin":
                with tempfile.TemporaryDirectory(
                    prefix=".electron-refresh-",
                    dir=str(target_path),
                ) as transaction_root_raw:
                    transaction_root = Path(transaction_root_raw)
                    staged_dist = transaction_root / "dist"
                    shutil.copytree(dist_dir, staged_dist, symlinks=True)
                    prepare_staged_runtime(staged_dist)
                    if not electron_runtime_is_usable(
                        staged_dist,
                        expected_version,
                    ):
                        raise RuntimeError("staged Electron refresh failed runtime validation")
                    swap_staged_runtime(
                        target_path,
                        staged_dist,
                        expected_version,
                        transaction_root,
                    )
        else:
            health, diagnostic = electron_runtime_health(dist_dir, expected_version)
            if health == "platform-dependency":
                raise RuntimeError(
                    "Electron is installed but Linux desktop libraries are missing: "
                    f"{diagnostic}. Install the Electron/GTK runtime libraries for "
                    "your distribution"
                )
            if dist_dir.exists() or dist_dir.is_symlink():
                detected = electron_runtime_version(
                    dist_dir,
                    include_recorded=False,
                )
                print(
                    "Replacing unusable or mismatched Electron runtime "
                    f"(found {detected}, expected {expected_version})..."
                )
            _download_and_install_runtime(target_path, expected_version)

        status = finalize_electron_install(
            target_path,
            dist_dir,
            refresh_app=refresh_app,
            adopt_app=adopt_app,
            pin_dock=pin_dock,
        )
        print(f"Electron {expected_version} is synchronized -> {target_dir}")
        return status


def _download_and_install_runtime(target_path: Path, version: str) -> None:
    """Download, verify, prepare, and transactionally install one runtime."""
    if target_path.is_symlink() or target_path.parent.is_symlink():
        raise RuntimeError(f"refusing symlinked Electron target: {target_path}")
    try:
        target_path.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(f"could not create Electron target: {target_path}") from exc
    if target_path.is_symlink() or not target_path.is_dir():
        raise RuntimeError(f"refusing unsafe Electron target: {target_path}")

    url = get_download_url(version)
    archive_name = url.rsplit("/", 1)[-1]
    print(f"Downloading Electron {version}...")
    print(f"  {url}")

    with tempfile.NamedTemporaryFile(suffix=".zip", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        req = urllib.request.Request(url, headers={"User-Agent": "vibe-view"})
        with urllib.request.urlopen(req, timeout=NETWORK_TIMEOUT_SECONDS) as resp:
            total = int(resp.headers.get("content-length", 0))
            downloaded = 0
            with tmp_path.open("wb") as stream:
                while True:
                    chunk = resp.read(65536)
                    if not chunk:
                        break
                    stream.write(chunk)
                    downloaded += len(chunk)
                    if total:
                        pct = downloaded / total * 100
                        mb = downloaded / (1024 * 1024)
                        total_mb = total / (1024 * 1024)
                        print(
                            f"\r  {mb:.0f}/{total_mb:.0f} MB ({pct:.0f}%)",
                            end="",
                            flush=True,
                        )
            print()

        verify_download_checksum(tmp_path, version, archive_name)
        print("Extracting...")
        with tempfile.TemporaryDirectory(
            prefix=".electron-stage-",
            dir=str(target_path),
        ) as transaction_root_raw:
            transaction_root = Path(transaction_root_raw)
            staged_dist = transaction_root / "dist"
            staged_dist.mkdir()
            system = platform.system().lower()
            if system == "darwin":
                subprocess.run(
                    ["ditto", "-xk", str(tmp_path), str(staged_dist)],
                    check=True,
                )
            elif shutil.which("unzip"):
                subprocess.run(
                    ["unzip", "-qo", str(tmp_path), "-d", str(staged_dist)],
                    check=True,
                )
            else:
                _extract_zip_preserving_permissions(tmp_path, staged_dist)

            executable = staged_dist / _binary_relpath()
            if not executable.is_file():
                raise RuntimeError("downloaded Electron archive is missing " + _binary_relpath())
            if system != "windows":
                executable.chmod(0o755)
            detected_version = electron_runtime_version(
                staged_dist,
                include_recorded=False,
            )
            if detected_version != version:
                raise RuntimeError(
                    "downloaded Electron version did not match the requested "
                    f"version: expected {version}, got {detected_version}"
                )
            prepare_staged_runtime(staged_dist)
            if not electron_runtime_is_usable(staged_dist, version):
                _detected, diagnostic = _electron_binary_probe(executable)
                detail = f": {diagnostic}" if diagnostic else ""
                if system == "linux":
                    detail += (
                        ". Install the Electron/GTK runtime libraries for your Linux distribution"
                    )
                raise RuntimeError(f"staged Electron runtime failed validation{detail}")
            swap_staged_runtime(
                target_path,
                staged_dist,
                version,
                transaction_root,
            )
    finally:
        tmp_path.unlink(missing_ok=True)


def main(argv: list[str] | None = None) -> int:
    """Run the installer CLI and preserve blocked-refresh exit semantics."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", nargs="?", help="Electron version to install")
    parser.add_argument(
        "--refresh-app",
        action="store_true",
        help="refresh the source-backed desktop app; never replace a packaged app",
    )
    parser.add_argument(
        "--adopt-app",
        action="store_true",
        help="let this checkout replace a source app owned by another checkout",
    )
    parser.add_argument(
        "--dock",
        action="store_true",
        help="pin the source-backed desktop app to the macOS Dock",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="check the reviewed Electron runtime without changing files",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="remove this checkout's recognized runtime and source desktop app",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="preview --uninstall without changing files",
    )
    args = parser.parse_args(argv)
    if args.adopt_app and not args.refresh_app:
        parser.error("--adopt-app requires --refresh-app")
    if args.dock and args.check:
        parser.error("--dock cannot be combined with --check")
    if args.check and (args.refresh_app or args.adopt_app):
        parser.error("--check cannot be combined with desktop refresh options")
    if args.uninstall and (
        args.version or args.check or args.refresh_app or args.adopt_app or args.dock
    ):
        parser.error("--uninstall cannot be combined with install/check options")
    if args.dry_run and not args.uninstall:
        parser.error("--dry-run requires --uninstall")
    if args.uninstall:
        via_sudo = bool(os.environ.get("SUDO_USER"))
        root_user = hasattr(os, "geteuid") and os.geteuid() == 0
        gitlab_ci = os.environ.get("CI") == "true" and os.environ.get("GITLAB_CI") == "true"
        elevated = os.name == "posix" and (via_sudo or (root_user and not gitlab_ci))
        if elevated:
            print(
                "Refusing to uninstall Electron as root or through sudo. "
                "Run the command as the regular user who installed vibe-view.",
                file=sys.stderr,
            )
            return 2
        uninstall_electron(dry_run=args.dry_run)
        return 0
    if args.check:
        target = Path(__file__).parent / "node_modules" / "electron" / "dist"
        version = args.version or configured_electron_version()
        if electron_runtime_is_usable(target, version):
            return 0
        health, diagnostic = electron_runtime_health(target, version)
        if health == "platform-dependency":
            print(
                "Electron is installed but Linux desktop libraries are missing: "
                f"{diagnostic}\nInstall the Electron/GTK runtime libraries for your "
                "distribution.",
                file=sys.stderr,
            )
            return 2
        return 1
    desktop_status = install_electron(
        args.version,
        refresh_app=args.refresh_app,
        adopt_app=args.adopt_app,
        pin_dock=args.dock,
    )
    if args.refresh_app and desktop_status in {
        "packaged",
        "unknown",
        "foreign-source",
    }:
        print(
            f"Desktop refresh was not completed (status: {desktop_status}).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
