"""Sphinx configuration for the vibe-view documentation.

Build locally with ``make html`` (from this directory) or
``sphinx-build -b html docs/ docs/_build/html`` from the repository root.
``scripts/build_site.sh`` is what CI runs; it wraps the same command and adds
``robots.txt`` / ``sitemap.xml`` / ``.build-info``.

This file deliberately mirrors the shape of vibe-qc's ``docs/conf.py``
(project 34) -- same theme, same static path, same substitution mechanism --
so the two sites read as one project when they sit side by side under
https://vibe-qc.com/.

Naming convention
-----------------
* The human-facing brand is **vibe-view** (with hyphen), and it is also the
  shell command. Use this in docs prose, titles, page headers.
* The Python distribution and import package is ``vibeview`` (no hyphen),
  because Python identifiers cannot carry dashes; ``import vibeview`` is what
  users type in code. Use ``vibeview`` inside code snippets only.
"""

from __future__ import annotations

import contextlib
import datetime
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent

# Make the vibe-view package importable when Sphinx runs autodoc. Unlike
# vibe-qc there is no compiled extension to build first: ``vibeview`` is pure
# Python, so an editable install is enough for the API reference to render.
sys.path.insert(0, str(_REPO_ROOT / "src"))


# --- Project metadata ------------------------------------------------------

project = "vibe-view"
author = "Michael F. Peintinger"
copyright = f"{datetime.date.today().year}, {author}"


def _read_release() -> str:
    """Version of the documented tree.

    Prefer the installed distribution metadata, so a docs build reports what
    its environment actually has -- which is what both a developer's venv and
    the CI docs job give it, since the ``[docs]`` extra installs the package.
    Fall back to parsing ``pyproject.toml`` from the source tree, so a bare
    ``sphinx-build`` in a checkout without that install still renders.
    """
    try:
        from importlib.metadata import PackageNotFoundError
        from importlib.metadata import version as _pkg_version

        try:
            return _pkg_version("vibeview")
        except PackageNotFoundError:
            pass
    except ImportError:
        pass
    try:
        import tomllib

        with open(_REPO_ROOT / "pyproject.toml", "rb") as f:
            return str(tomllib.load(f)["project"]["version"])
    except Exception:
        return "0.0.0"


release = _read_release()
version = ".".join(release.split(".")[:2])


# --- Extensions ------------------------------------------------------------

extensions = [
    # Markdown with roles and directives. Every page here is MyST Markdown;
    # there is no .rst source in this tree.
    "myst_parser",
    # Autogenerate the Python SDK reference from docstrings.
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",  # NumPy / Google style docstrings
    # Cross-link to Python + NumPy docs.
    "sphinx.ext.intersphinx",
    # Add [source] links next to autogenerated headings.
    "sphinx.ext.viewcode",
    # Copy-button on fenced code blocks.
    "sphinx_copybutton",
    # Grid cards / dropdowns / tabs.
    "sphinx_design",
]

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

myst_enable_extensions = [
    "colon_fence",  # ::: fenced admonitions
    "deflist",  # term / definition lists
    "linkify",  # auto-link bare URLs
    "substitution",  # {{release}} / {{codename}} below
    "tasklist",
]
myst_heading_anchors = 3


# --- Release codename ------------------------------------------------------
#
# The catalogue is canonical in ``vibeview.codenames`` so the CLI banner, the
# desktop About box and this site share one source of truth. Load that module
# standalone rather than importing the ``vibeview`` package: a bare
# ``sphinx-build`` in a checkout without the ``[docs]`` install must still
# render the site, and ``import vibeview`` would need the whole runtime for
# the sake of one dict.
def _load_codenames_module():
    import importlib.util

    module_path = _REPO_ROOT / "src" / "vibeview" / "codenames.py"
    if not module_path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("_vv_codenames_for_docs", module_path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception:
        return None
    return module


_codenames = _load_codenames_module()
if _codenames is not None:
    RELEASE_CODENAMES = getattr(_codenames, "RELEASE_CODENAMES", {})
    _codename_lookup = getattr(_codenames, "codename_for_version", lambda rel: None)
else:  # pragma: no cover - only when the module is missing entirely
    RELEASE_CODENAMES = {}

    def _codename_lookup(rel):  # type: ignore[misc]
        return None


codename = _codename_lookup(release) or "(unnamed)"

myst_substitutions = {
    "release": release,
    "version": version,
    "codename": codename,
}


# --- Autodoc ---------------------------------------------------------------

autosummary_generate = True
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
}
autodoc_member_order = "bysource"
autodoc_typehints = "description"

# The public SDK is re-exported from ``vibeview/__init__.py``, which imports
# the renderer stack. A docs container without pyvista / plotly / matplotlib
# still has to render the API page, so mock the heavy third-party roots. This
# is the same trick vibe-qc uses for its compiled core, applied to the
# viewer's rendering dependencies instead.
autodoc_mock_imports = [
    "matplotlib",
    "plotly",
    "pyvista",
    "trame",
    "trame_vtk",
    "trame_vuetify",
    "vtk",
    "vtkmodules",
]

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
}


# --- HTML output -----------------------------------------------------------

html_theme = "furo"
html_title = "vibe-view documentation"
html_static_path = ["_static"]
html_favicon = "_static/logo/vibe-view-favicon.svg"
templates_path = ["_templates"]
html_css_files = ["custom.css"]  # shared with vibe-qc; see _static/custom.css

# Public canonical URL. Private deployment configuration is maintained separately.
html_baseurl = "https://vibe-qc.com/vibe-view/docs/"
html_context = {"site_url": html_baseurl}

html_theme_options = {
    "sidebar_hide_name": True,
    "light_logo": "logo/vibe-view-wordmark-light.svg",
    "dark_logo": "logo/vibe-view-wordmark-dark.svg",
    # Public repository links are independent of private deployment settings.
    "footer_icons": [
        {
            "name": "Source",
            "url": "https://github.com/vibe-qc/vibe-view",
            "html": "",
            "class": "fa-brands fa-solid fa-github fa-2x",
        },
    ],
    "navigation_with_keys": True,
}


# --- Other -----------------------------------------------------------------

nitpicky = False

exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    # Developer tooling that lives in docs/ and is cited from the root
    # ledgers (HANDOVER.md, AUDIT_2026-*.md) by its docs/ path. Sphinx does
    # not read .py as source anyway; listing them is documentation of intent
    # for whoever wonders why they are in here.
    "bench_*.py",
    "capture_*.py",
    "interact_controls.py",
    "qa_*.py",
]

suppress_warnings = [
    "myst.header",  # some included pages start at h2 on purpose
    # Autosummary stubs are linked from the module page, not a toctree.
    "toc.not_included",
]


# --- Known-unfixable warnings ----------------------------------------------
#
# A blanket ``suppress_warnings = ["myst.xref_missing"]`` would silence these
# and also silence a typo in installation.md, which is the one thing we most
# want ``make strict`` to catch. Suppress the specific messages instead, the
# way vibe-qc's conf.py does, so anything NEW still warns.
#
# Two groups, both links that resolve on GitLab but not through Sphinx's
# document graph:
#
#  * ``ROADMAP_AVOGADRO_PARITY.md`` is an internal engineering note that
#    predates this site and cross-links the pre-split monorepo layout.
#    Rewriting its links would edit a historical document to suit a
#    renderer.
#  * ``CHANGELOG.md`` / ``CONTRIBUTING.md`` are ``{include}``d from the
#    repository root, so their sibling-file links resolve against docs/
#    rather than the root.
#
# Seven targets, eight warnings -- vibe_view_live_reload.md is referenced
# twice. Every entry names a specific target. If one stops appearing, delete
# it: a stale entry here silently widens the gate.
_KNOWN_MISSING_XREFS = (
    "../../docs/user_guide/vibe_view_vq_jobs.md",
    "../../docs/user_guide/vibe_view_live_reload.md",
    "../../docs/user_guide/vibe_view_python_api.md",
    "electron/PUBLISHING",
    "README.md#history",
    "SECURITY.md",
    "LICENSE",
)


class _SuppressKnownMissingXrefs:
    """Drop the warnings listed in ``_KNOWN_MISSING_XREFS``, and nothing else.

    Two details, both learned the hard way, both load-bearing:

    1. It attaches to the **handlers** on the ``sphinx`` logger, not to the
       logger. MyST logs through child loggers (``sphinx.myst_parser...``),
       and a filter on a parent logger is *not* applied to records
       propagating up from a child -- only handlers are inherited that way.
       Filtering at the logger silences nothing, quietly.
    2. It is inserted at the **front** of the handler's filter chain.
       Sphinx's own ``WarningSuppressor`` (the filter that implements
       ``suppress_warnings``) increments ``app._warncount`` as a side effect
       of accepting a record, and ``-W`` fails the build on that count.
       Appending puts us after it: the message stops being printed but the
       build still fails with "8 warnings" and nothing visible to explain
       why. Running first means the record is dropped before it is counted.
    """

    def filter(self, record) -> bool:
        message = str(record.msg)
        if "%" in message and record.args:
            # A record whose args do not match its format string is not our
            # problem to fix -- keep the raw template and carry on filtering.
            with contextlib.suppress(TypeError, ValueError):
                message = record.getMessage()
        location = getattr(record, "location", "") or ""
        haystack = f"{message} {location}"
        if "not found" not in haystack and "Unknown source document" not in haystack:
            return True
        return not any(target in haystack for target in _KNOWN_MISSING_XREFS)


def setup(app):
    """Install the known-warning filter on the sphinx logger's handlers.

    Registered through ``setup`` rather than at import time so Sphinx's own
    logging is already configured when we attach to it.
    """
    import logging

    predicate = _SuppressKnownMissingXrefs()
    for handler in logging.getLogger("sphinx").handlers:
        # Front of the chain -- see the class docstring for why appending is
        # not enough. `filters` is a plain list on logging.Handler.
        handler.filters.insert(0, predicate)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
